### ISSUE TITLE
Support for fixing parts of the binder?

### ISSUE THREAD

**Issue by harshagrawal13** [martinpacesa/BindCraft#1]
I want to design a binder where I hold a the scaffold sequence fixed and only hallucinate / redesign my loops that are in contact with the protein. Is there a way to specify that?

**Comment by martinpacesa** [comment]
Hi! This is not implemented yet, but we hope to put out that feature by the end of the year.

**Comment by gezmi** [comment]
Hi! How is this coming around?

**Comment by martinpacesa** [comment]
Will be part of BindCraft2 :)
