### ISSUE TITLE
still about installation

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#10]
I run "bash install_bindcraft.sh --pkg_manager 'conda' "
But it returns back:
You must provide the conda_env and pkg_manager options.

It seems that I have to give a value to conda_env?

**Comment by finexzhi** [comment]
I use the command "conda info --base" to find the path to "conda_env".

run the line then:
bash install_bindcraft.sh --pkg_manager 'conda' --conda_env 'path'

**Comment by martinpacesa** [comment]
Did you donwload the new version of the install script? If it asks for conda_env then it's the previous version

**Comment by finexzhi** [comment]
I am using the ubuntu terminal and run Linux applications on windows.
https://ubuntu.com/download
For this version, conda has to be installed in order to run the command.

To install Conda on Ubuntu, you can follow these steps: Step 1: Download the Miniconda Installer Miniconda is a smaller, more lightweight version of Anaconda that includes only Conda and Python. You can later install any packages you need using Conda. 1. Open a terminal in Ubuntu. 2. Download the Miniconda installer using wget: wget [https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh](https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepo.anaconda.com%2Fminiconda%2FMiniconda3-latest-Linux-x86_64.sh&data=05%7C02%7C%7C72da966c850a4e2abde608dce475f29a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638636442435666334%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=r3NU6USiyZ3mezIdqHZyXfPP8aYnBMEPdmLT1phIRpQ%3D&reserved=0) Step 2: Run the Installer 3. Run the installer script: bash Miniconda3-latest-Linux-x86_64.sh 4. Follow the on-screen instructions: • Press Enter to scroll through the license agreement. • Type yes to accept the license. • When asked for the installation location, you can press Enter to accept the default (/home/username/miniconda3) or specify a custom directory. Step 3: Initialize Conda 5. After installation is complete, initialize Conda by running: source ~/miniconda3/bin/activate 6. Then, run this command to configure your shell (e.g., bash): conda init 7. Restart your terminal or run: source ~/.bashrc Step 4: Verify the Installation 8. Check that Conda is installed and available by running: conda --version You should see the version of Conda that you just installed. Optional: Install Mamba (If Needed) If you want to install Mamba (a faster package manager for Conda), use: conda install mamba -n base -c conda-forge You’re Done! You now have Conda installed on your Ubuntu system. You can create environments, install packages, and manage dependencies using Conda. For example, to create a new environment with Python 3.8: conda create -n myenv python=3.8 Activate this environment with: conda activate myenv

**Comment by martinpacesa** [comment]
Yes, you will first need to install conda on your ubuntu system to run the pipeline.

**Comment by finexzhi** [comment]
The miniconda3 installed seems to be a latest version but still need conda_env .
But this is not a problem now.
