### ISSUE TITLE
IndexError: string index out of range when fixing interface residues

### ISSUE THREAD

**Issue by Yutong0420** [martinpacesa/BindCraft#102]
Hi, I encountered the following error while running BindCraft with "target_hotspot_residues": "null" in the settings file:

Fixing interface residues:
Traceback (most recent call last):
  File "/app/bindcraft.py", line 172, in <module>
    mpnn_trajectories = mpnn_gen_sequence(trajectory_pdb, binder_chain, trajectory_interface_residues, advanced_settings)
  File "/app/functions/colabdesign_utils.py", line 357, in mpnn_gen_sequence
    mpnn_model.prep_inputs(pdb_filename=trajectory_pdb, chain=design_chains, fix_pos=fixed_positions, rm_aa=advanced_settings["omit_AAs"])
  File "/usr/local/lib/python3.10/dist-packages/colabdesign/mpnn/model.py", line 81, in prep_inputs
    p = prep_pos(fix_pos, **pdb["idx"])["pos"]
  File "/usr/local/lib/python3.10/dist-packages/colabdesign/shared/prep.py", line 19, in prep_pos
    if i[0].isalpha():
IndexError: string index out of range
This occurred immediately during the "Fixing interface residues" step. The target_hotspot_residues was set to null, as I intended for BindCraft to automatically detect the hotspot residues.

Would this issue be related to how null is handled in the code? If needed, I can provide additional details or the input files.

Thanks for your help!

**Comment by martinpacesa** [comment]
It's because "null" is handled as a string. Just leave it empty ""

**Comment by Yutong0420** [comment]
Thank you for your response. I followed your suggestions, but the issue still persists. The error does not occur immediately but appears randomly while processing the nth operation
