### ISSUE TITLE
Missing indicators of what to learn from output to improve results.

### ISSUE THREAD

**Issue by bifxcore** [martinpacesa/BindCraft#103]
I have now tried for weeks to get a binder to stick. I am using the hints that I could gather:
- truncate target as much as possible
- remove disordered parts
- update local repo to keep up with commits
- try different weights and filters
- different hot spots

This led me to exactly *1* design accepted so far. Better than nothing :-) However, how to build on this lone success to improve outcome? 

Logically, you would think that looking at the good design, I would be able to figure out what target residues ended up in the interface and use those in the next run. I could also look at the good trajectories and infer the common residues that are present in all interfaces. I tested both of these strategies, and I got 0 designs passing.

Please can you give me a hint on how to use the results of failed runs to try to increase the number of passing designs? How do I infer from the logs and heaps of output WHY the second stage keeps failing (No accepted MPNN designs found for this trajectory)?

**Comment by mdppdm** [comment]
I have the same question. From  my last job there are some reasonable relaxed binders, but the job stopped (see below).

How do I continue this job with a lower acceptance rate? And/or, as bifxcore asked, how to I optimize the settings based on the results from the first job?

This could be a great tool, but I would like to be able to use it efficiently. 

Trajectory successful, final pLDDT: 0.87
Trajectory successful, final pLDDT: 0.74
Trajectory successful, final pLDDT: 0.88
Trajectory successful, final pLDDT: 0.84
Trajectory successful, final pLDDT: 0.8
Trajectory successful, final pLDDT: 0.82
Trajectory successful, final pLDDT: 0.85
Trajectory successful, final pLDDT: 0.89
Trajectory successful, final pLDDT: 0.88
The ratio of successful designs is lower than defined acceptance rate! Consider changing your design settings!

**Comment by martinpacesa** [comment]
Generally, the thing that affects designs success the most is the target and choice of hotspots. It could be that your target is simply too hard for the pipeline to do. However, if you got one, there is hope! How many trajectories (based on entries in trajectory_stats.csv) did you have to do to get the 1?

**Comment by bifxcore** [comment]
> However, if you got one, there is hope! How many trajectories (based on entries in trajectory_stats.csv) did you have to do to get the 1?

144.

**Comment by bifxcore** [comment]
So I think I may have found a lead. I'm testing an 'obvious' system with 2 quasi-identical models of the same sequence, one produced by AF3 and one by RoseTTAFold. Guess which one produces 'Base AF2 filters not passed ...No accepted MPNN designs found for this trajectory' despite successful Stage 4 trajectories with  final pLDDT > 0.9 ?
That's right: BindCraft appears to choke on targets modelled by RoseTTAFold. For me that's bad news: the RoseTTAFold models have better geometry in this particular case. 

How do I get BindCraft to treat RoseTTAFold models like AF3 models? Is there maybe some simple PDB processing I could do?

**Comment by martinpacesa** [comment]
That's probably very little! For hard targets one might need to sample up to 3000.

**Comment by bifxcore** [comment]
> one might need to sample up to 3000

The run died with "The ratio of successful designs is lower than defined acceptance rate". Current acceptance_rate=0.01. I suppose I could set it to zero and let it run for a while.

**Comment by martinpacesa** [comment]
You can set enable_rejection_check to false
