### ISSUE TITLE
Continuing jobs and optimization

### ISSUE THREAD

**Issue by mdppdm** [martinpacesa/BindCraft#104]
There are some reasonable relaxed binders (9/100 requested), but the job stopped (see below).

How do I continue this job with a lower acceptance rate? What is the default acceptance rate? How to I optimize the settings based on the results from the first job?

Trajectory successful, final pLDDT: 0.87
Trajectory successful, final pLDDT: 0.74
Trajectory successful, final pLDDT: 0.88
Trajectory successful, final pLDDT: 0.84
Trajectory successful, final pLDDT: 0.8
Trajectory successful, final pLDDT: 0.82
Trajectory successful, final pLDDT: 0.85
Trajectory successful, final pLDDT: 0.89
Trajectory successful, final pLDDT: 0.88
The ratio of successful designs is lower than defined acceptance rate! Consider changing your design settings!

**Comment by martinpacesa** [comment]
Set enable_rejection_check to false and continue generating into the same output folder
