### ISSUE TITLE
I can't find the compressed result file?

### ISSUE THREAD

**Issue by Eager-to-earn-money-standing-up** [martinpacesa/BindCraft#107]
When I ran through the sample code you gave, I finally got the result that the file was compressed and deleted. After that, I ran my short peptide again while modifying some parameters of the script, but I still didn't find the result file in the corresponding folder where the results were stored. Why?

**Comment by martinpacesa** [comment]
Could you please explain what you are trying to achieve? I am not sure I understand

**Comment by Eager-to-earn-money-standing-up** [comment]
I want to design some binders through a tool you provided, but when a program is finished, the result is compressed into the specified folder, but afterwards the result file or compressed result file is not found in the corresponding folder

**Comment by martinpacesa** [comment]
Are you using the colab notebook? Did you check the output folder in your Google drive? The results should not be compressed

**Comment by martinpacesa** [comment]
The final sequences and statistics are in the final_design_stats.csv and the models are in the Accepted/ folder.

**Comment by Eager-to-earn-money-standing-up** [comment]
But it didn't find the Accept folder you said in the pull code on the cluster

**Comment by martinpacesa** [comment]
What do you see when you open your PDL1_results folder

**Comment by Eager-to-earn-money-standing-up** [comment]
empty

**Comment by martinpacesa** [comment]
what path did you enter into the target settings json? It seems you have a dot in your path, which would mess up the saving paths

**Comment by Eager-to-earn-money-standing-up** [comment]
![屏幕截图 2024-11-25 203715](https://github.com/user-attachments/assets/563ec611-739c-4555-9752-352897859ba5)

**Comment by martinpacesa** [comment]
yeah the dots in your file paths are definitely causing problems, I am not sure where it would save it on your filesystem, but certainly not in PDL1_results. Search your filesystem for the Binder_results folder, or a folder called Accepted/

**Comment by Eager-to-earn-money-standing-up** [comment]
![image](https://github.com/user-attachments/assets/4e879a61-707a-4271-bc90-95e07bf531f7)
Although the design amount set by the entire script was not completed, the whole process took more than 10 hours, and in the end, there was no output result

**Comment by Eager-to-earn-money-standing-up** [comment]
Sorry, the problem has been solved  Thanks
