### ISSUE TITLE
comment :: inconsistency bindcraft.py vs bindcraft.slurm

### ISSUE THREAD

**Issue by EricDeveaud** [martinpacesa/BindCraft#110]
Hello.

`bindccraft.py` can be run without specfying settings_filter nor settings_advanced and will use, in this case, the following defaults
`settings_filters/default_filters.json`
`settings_advanced/default_4stage_multimer.json`

while `bindcraft.slurm` have hard requirement for both. well sort off, as if not provided thoses values are transferd to bindcraft.py as empty ones.

**Comment by martinpacesa** [comment]
Good catch, thank you! Will be fixed in the next version
