### ISSUE TITLE
suggestion :: log settings used 

### ISSUE THREAD

**Issue by EricDeveaud** [martinpacesa/BindCraft#111]
Hello, 

maybee you would want to consider to display the settings_filter used, or at least corresponding file name and same for used settings_advanced.
or save a copy of the file in the result dir. 
this may helps  for reproductibilty

regards

Eric

**Comment by EricDeveaud** [comment]
NB of course this is for pure bindcraft.py run as bindcraft.slurm does it.

to be clear I would transfert the display of those information to main script instead of slurm wrapper.

regards

Eric

**Comment by martinpacesa** [comment]
Good suggestion, will be added in the next version
