### ISSUE TITLE
suggestion :: move gpu jax detection after argument parsing

### ISSUE THREAD

**Issue by EricDeveaud** [martinpacesa/BindCraft#112]
Hello, 

I would suggest to allow bindcraft.py to be run on non GPU nodes, at least to have the help displayed.

on our cluster submit node is CPU only. so our users, currently, can't  run `bindcraft.py --help`

I would suggest the following.
NB patch embeds the display of used settings (see: https://github.com/martinpacesa/BindCraft/issues/111)

```
--- bindcraft.py.ori	2024-11-26 13:23:15.837513020 +0100
+++ bindcraft.py	2024-11-26 14:23:39.054009372 +0100
@@ -4,8 +4,6 @@
 ### Import dependencies
 from functions import *

-# Check if JAX-capable GPU is available, otherwise exit
-check_jax_gpu()

 ######################################
 ### parse input paths
@@ -20,9 +18,17 @@

 args = parser.parse_args()

+# Check if JAX-capable GPU is available, otherwise exit
+check_jax_gpu()
+
 # perform checks of input setting files
 settings_path, filters_path, advanced_path = perform_input_check(args)

+print("Running the BindCraft pipeline")
+print("Running binder design for target:", settings_path)
+print("Design settings used:", advanced_path)
+print("Filtering designs based on:", filters_path)
+
 ### load settings from JSON
 target_settings, advanced_settings, filters = load_json_settings(settings_path, filters_path, advanced_path)
```

Eric

Edit: fix typo in patch

**Comment by martinpacesa** [comment]
Hi, This is intentional, for non-expert users to not attempt to run on CPU because while it can still run, it is excruciatingly slow. You can comment out the line  check_jax_gpu()

**Comment by EricDeveaud** [comment]
it is just to allow to display the help even on non GPU node, as our submit node is.

`check_jax_gpu()` is just moved **after** options parsing. thus will abort and won't run on CPU node

it is just to avoid to have to srun it on specific qos//partition

Eric
