### ISSUE TITLE
error on Tesla V100S-PCIE-32GB cards

### ISSUE THREAD

**Issue by rukibuki** [martinpacesa/BindCraft#114]
I am suing the same bindcraft version (1.2) and same bindcraft conda env on all our nodes. When I tried to start copies of the same run (same filter, advanced and target,json)  on multiple GPU nodes, the only node running with Tesla V100 cards gave the below error. The V100 node uses the same nvidia driver version and cuda version as the other nodes. something I can do to fix this? The v100s have 32gb of memory, which is you minimum amount of vram to run bindcraft on.

Stage 1: Test Logits
E1127 20:18:50.812097  150728 buffer_comparator.cc:157] Difference at 0: 96.2491, expected 96.2491
E1127 20:18:50.840553  150728 buffer_comparator.cc:157] Difference at 1: 97.6674, expected 97.6674
E1127 20:18:50.844962  150728 buffer_comparator.cc:157] Difference at 2: 94.0413, expected 94.0413
E1127 20:18:50.864918  150728 buffer_comparator.cc:157] Difference at 3: 97.4507, expected 97.4507
E1127 20:18:50.868603  150728 buffer_comparator.cc:157] Difference at 4: 94.7962, expected 94.7962
E1127 20:18:50.872160  150728 buffer_comparator.cc:157] Difference at 5: 98.3404, expected 98.3404
E1127 20:18:50.875985  150728 buffer_comparator.cc:157] Difference at 6: 101.752, expected 101.752
E1127 20:18:50.879264  150728 buffer_comparator.cc:157] Difference at 7: 97.9409, expected 97.9409
E1127 20:18:50.882718  150728 buffer_comparator.cc:157] Difference at 8: 105.633, expected 105.633
E1127 20:18:50.891108  150728 buffer_comparator.cc:157] Difference at 9: 97.9142, expected 97.9142
2024-11-27 20:18:50.899862: E external/xla/xla/service/gpu/autotuning/gemm_algorithm_picker.cc:348] Results mismatch between different GEMM algorithms. This is likely a bug/unexpected loss of precision.
E1127 20:18:50.907938  150728 buffer_comparator.cc:157] Difference at 0: 96.2491, expected 96.2491

**Comment by rukibuki** [comment]
-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100S-PCIE-32GB          On  |   00000000:3D:00.0 Off |                    0 |
| N/A   24C    P0             24W /  250W |       0MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  Tesla V100S-PCIE-32GB          On  |   00000000:3E:00.0 Off |                    0 |
| N/A   22C    P0             24W /  250W |       0MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  Tesla V100S-PCIE-32GB          On  |   00000000:88:00.0 Off |                    0 |
| N/A   24C    P0             24W /  250W |       0MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  Tesla V100S-PCIE-32GB          On  |   00000000:89:00.0 Off |                    0 |
| N/A   23C    P0             24W /  250W |       0MiB /  32768MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------

For the driver version cuda 12.x is recommended. I can try to module load cuda 11.8

**Comment by martinpacesa** [comment]
We have had troubles running it on V100 and CUDA 11 recently, but I admit I did not spend much time debugging. If you find a solution, let us know!

**Comment by rukibuki** [comment]
pip uninstall -y jax jaxlib jax-cuda12-pjrt jax-cuda12-plugin

pip install jax[cuda]==0.4.30 jaxlib==0.4.30 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html


 pip list | grep jax
jax                       0.4.30
jax-cuda12-pjrt           0.4.30
jax-cuda12-plugin         0.4.30
jaxlib                    0.4.30

and then it works. 

The other nodes have this:

 pip list | grep jax
jax                       0.4.30
jax-cuda12-pjrt           0.4.33
jax-cuda12-plugin         0.4.33
jaxlib                    0.4.30


but they work.

**Comment by martinpacesa** [comment]
that's great to know, thank you!!
