### ISSUE TITLE
Too many tries in `fill_missing_atoms` error

### ISSUE THREAD

**Issue by shivashankarv** [martinpacesa/BindCraft#115]
Hi,

I get the following error while executing it on the Google Collab notebook, while executing the `Run BindCraft` cell.

File: /home/benchmark/rosetta/source/src/core/conformation/Conformation.cc:1933
[ ERROR ] UtilityExitException
ERROR: too many tries in fill_missing_atoms!

**Comment by martinpacesa** [comment]
Please make sure you trimmed your input pdb correctly and there are no partial residues

**Comment by astomer2** [comment]
This is generally because the structure of the input rosetta does not meet its standards. I recommend adding a repack processing step in the rosetta filter section to ensure that the structure meets the specifications.
