### ISSUE TITLE
RMSD weight

### ISSUE THREAD

**Issue by astomer2** [martinpacesa/BindCraft#116]
First of all, thank you for your excellent work. The community thrives because of you. When I was looking at your code, I was very interested in your filtering strategy, because we can't always find a suitable standard to filter the structures generated by AFD or RF+MPNN, so I carefully checked your weight file. I found that your weights for hotspot_RMSDhe Binder_RMSD are positive and usually large. Generally speaking, if the RMSD of the target structure in a trajectory is large, doesn't it mean that the prediction is not very reliable? The weight treatment in the code is a simple addition, so if the RMSD is large, will this cause the ranking of unreliable trajectories to rise?

**Comment by martinpacesa** [comment]
Thank you for the kind works! I think you were looking at the filter json file, those are not weights but hard cutoffs of the value to filter against. In the case of RMSD it is the Calpha RMSD in Angstrom. "higher": false flag indicates that the value for the passing design should NOT be higher than that. In the case of Binder_RMSD it is to make sure that the binder in bound and unbound form does not have a radically different structure

**Comment by astomer2** [comment]
Thanks for your quick reply, this means we are just doing a cutoffs of an attribute, right? Different binders apply different cutoffs .

**Comment by martinpacesa** [comment]
You can apply different cutoffs if you wish, but these have been pretty generalisable so far for a variety of different targets

**Comment by astomer2** [comment]
Ok, thanks for your reply, I will close this issue
