### ISSUE TITLE
a few error messages during the installation

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#12]
![thumbnail_IMG_3683](https://github.com/user-attachments/assets/55c91ed0-547d-4f3a-a7cd-13423a166a55)
![thumbnail_IMG_3684](https://github.com/user-attachments/assets/9d8edb50-11f6-4b6f-a7bb-bcda272a1b9e)
![thumbnail_IMG_3685](https://github.com/user-attachments/assets/9a105cde-3014-4ba6-a507-b74cd88f5352)
![thumbnail_IMG_3686](https://github.com/user-attachments/assets/0b333cd3-f4b2-40a7-af9a-37ffb35713f0)
![thumbnail_IMG_3687](https://github.com/user-attachments/assets/8996a5b1-5ad4-4016-a6a1-9113a2b74761)
![thumbnail_IMG_3688](https://github.com/user-attachments/assets/0d5565b6-8dd1-423c-a4d6-a08afd79a5c3)
![thumbnail_IMG_3689](https://github.com/user-attachments/assets/57eeac6b-701b-49ab-8711-e75e2688b67f)

**Comment by martinpacesa** [comment]
This seems to be a conda issue rather than problem with the pipeline, unfortunately I cannot be of much help there

**Comment by finexzhi** [comment]
Thanks. You are right, here. I need to use another version of conda.

**Comment by finexzhi** [comment]
After I changed to anaconda3, the errors are reduced to only 3 now:
Py3Dmol, jax(cuba), matplotlib (shown in red in the above figures).

Do you think these will affect the normal functions of BindCraft?

Thanks!

**Comment by martinpacesa** [comment]
Hello, please refrain for starting multiple issues. The problems you have been describing show a corrupted installation of conda. I think once you try to reinstall, it should work, but pay close attention that you install the correct conda version for your hardware system
