### ISSUE TITLE
Release Artifacts are broken

### ISSUE THREAD

**Issue by AKluge** [martinpacesa/BindCraft#120]
The source code archives (zip and tar.gz) for version 1.1.0 and 1.2.0 aren't downloadable  and result on a 404 error

https://github.com/martinpacesa/BindCraft/releases/tag/v1.1.0

**Comment by xeniorn** [comment]
@AKluge it was either transient or it's an issue on your end. Seems to work fine.

**Comment by AKluge** [comment]
Yes it works now, strange tried it, from different machines including a cluster but looks like it works again
