### ISSUE TITLE
Design two binders simultaneously

### ISSUE THREAD

**Issue by riiichardh** [martinpacesa/BindCraft#121]
Using the BindCraft, is it possible to simultaneously generate two binders binding to different interfaces on one target protein? I am thinking of running the pipeline twice, where you used the output complex from the first round as your target in the second round. Are there other ways?

**Comment by martinpacesa** [comment]
not two at a time, but you can use target+binder1 as input into a second round

**Comment by riiichardh** [comment]
Thanks so much, @martinpacesa! I will try this method anyway.

Now I have another issue. After binder hallucination and optimization, I can get satisfying trajectories with low i_pae (~0.2). But after passing through MPNNsol, the i_pae usually becomes quite large (~0.8+). I know that the binder sequence has been changed a little bit by MPNNsol, but why has the i_pae significantly deteriorated? Do you have some suggestions in this case?
