### ISSUE TITLE
BindCraft minimum & optimal hardware requirements

### ISSUE THREAD

**Issue by doge4019** [martinpacesa/BindCraft#124]
Hello. 

I am setting up a work platform that can run BindCraft. Could you please tell me the minimum hardware requirements and the optimal hardware requirements for running BindCraft? I would greatly appreciate it.

**Comment by martinpacesa** [comment]
Well depends, I would recommend getting these GPUs: L40s, V100, A100, or H100. About 128 Gb RAM, several Tb of storage space, and at least 4 CPUs, ideally 32 or more (not for BindCraft but more general downstream usage of other tools). Technically it can run on any Linux computer with CUDA compatible GPU, but GPU memory limits how big your designs can be.

**Comment by doge4019** [comment]
Thank you for your quick reply! It helps a lot
