### ISSUE TITLE
Error from the Google Colab: Error tokenizing data. Expected 2857 fields in line 27, saw 5059

### ISSUE THREAD

**Issue by dshammers** [martinpacesa/BindCraft#125]
I mounted my drive and input the file path to my model as instructed, but now I'm getting the error given in the title. The full text is given below:

---------------------------------------------------------------------------
ParserError                               Traceback (most recent call last)
[<ipython-input-30-8a2960c70177>](https://localhost:8080/#) in <cell line: 6>()
      4 ####################################
      5 # Colab-specific: live displays
----> 6 num_sampled_trajectories = len(pd.read_csv(trajectory_csv))
      7 num_accepted_designs = len(pd.read_csv(final_csv))
      8 sampled_trajectories_label = HTML(value=f"<h3 style='color: #1f77b4;'>Sampled Trajectories: <span style='color: #1f77b4;'>{num_sampled_trajectories}</span></h3>")

3 frames
[/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/c_parser_wrapper.py](https://localhost:8080/#) in read(self, nrows)
    232         try:
    233             if self.low_memory:
--> 234                 chunks = self._reader.read_low_memory(nrows)
    235                 # destructive to chunks
    236                 data = _concatenate_chunks(chunks)

parsers.pyx in pandas._libs.parsers.TextReader.read_low_memory()

parsers.pyx in pandas._libs.parsers.TextReader._read_rows()

parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()

parsers.pyx in pandas._libs.parsers.TextReader._check_tokenize_status()

parsers.pyx in pandas._libs.parsers.raise_parser_error()

ParserError: Error tokenizing data. C error: Expected 2857 fields in line 27, saw 5059

Could I be doing something that caused this? The pdb file I'm using was generated by Boltz hosted on Tamarind Bio, if that matters.

**Comment by martinpacesa** [comment]
Can you send a screenshot of your settings.

**Comment by dshammers** [comment]
How do I do that for the Colab file?

**Comment by dshammers** [comment]
> Can you send a screenshot of your settings.

Is this what you're after?
![settings 1](https://github.com/user-attachments/assets/8b86e75b-7dfa-4b73-88dc-0343945e2fea)

**Comment by martinpacesa** [comment]
I mean your settings for design, the path, binder properties, etc

**Comment by dshammers** [comment]
Sorry about that, I didn't make the connection to the settings group that was listed.

![image](https://github.com/user-attachments/assets/8e9266ac-2f1c-4b1c-820a-4f1b2cbaabdf)
![image](https://github.com/user-attachments/assets/e14efcfa-83db-4478-84d2-a030390b6a2a)

**Comment by martinpacesa** [comment]
Yeah the problem is the https:// links everywhere. It needs to be linux links.  /content/drive/MyDrive/ already points to your google drive
