### ISSUE TITLE
the position of the N-terminal of the binder

### ISSUE THREAD

**Issue by july591** [martinpacesa/BindCraft#128]
hi, on what basis is the position of the N-terminal of the binder generated by bindcraft determined? The N-terminal of the generated binder is in a fixed position, but this is the opposite of where I want the sequence to be. How do I adjust this position?

**Comment by martinpacesa** [comment]
Not quite sure what you mean, can you give an example?

**Comment by july591** [comment]
> Not quite sure what you mean, can you give an example?
As an example with this protein, the red part in the middle is the generated binder. What I want is for the N-terminus and C-terminus to be positioned like this, with the N-terminus at the bottom and the C-terminus at the top. 
![1](https://github.com/user-attachments/assets/fe5b7c89-361c-4638-8785-024637ac6073)
but, the generated structure is the opposite of what I want, like this：
![2](https://github.com/user-attachments/assets/e2f44f05-b9b8-462f-9686-754b519e3bf7)

**Comment by martinpacesa** [comment]
Hmm, so currently there is no way to do that, but I suppose you could write a custom loss function to keep the N terminus as far away from the target as possible

**Comment by july591** [comment]
> Hmm, so currently there is no way to do that, but I suppose you could write a custom loss function to keep the N terminus as far away from the target as possible

Thank you for your reply
