### ISSUE TITLE
How can I parallelize bindcraft?

### ISSUE THREAD

**Issue by LAJ-THU** [martinpacesa/BindCraft#129]
I was running bindcraft on a server with 4 GPUs. I found that the process was put on all 4 GPUs but only the first GPU was utilized. How can I run bindcraft on all 4 GPUs? Does BindCraft support parallelization?

**Comment by linuxfold** [comment]
Put CUDA_VISIBLE DEVICES variable right before the Bindcraft command to specify the GPU:

CUDA_VISIBLE_DEVICES=0 python -u ./bindcraft.py --settings './settings_target/PDL1.json' --filters './settings_filters/default_filters.json' --advanced './settings_advanced/default_4stage_multimer.json'

**Comment by martinpacesa** [comment]
BindCraft can only run on one GPU at a time. But you can run 4 parallel instances of the same job into one output folder to speed things up
