### ISSUE TITLE
I failed to run run the binder design script

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#13]
I use nano to edit the settings_target/Json file. 
However, it did run the script using the sbatch command line.
Thanks
![thumbnail_IMG_3695](https://github.com/user-attachments/assets/87447648-7836-4437-8980-ceef6a8c5b96)
![thumbnail_IMG_3696](https://github.com/user-attachments/assets/c1d1ca62-4142-4340-b959-7db30d18c7cc)

**Comment by 21tesla** [comment]
(1) ensure that your environment is set up with "conda activate BindCraft"
(2) edit the settings_target file to point to the location of the files (it says /root but you're in the home directory ~ in the screenshot, are they the same? 
(3) if you are not running a batch system, try running the software directly with
python -u /root/BindCraft/bindcraft.py --settings '/root/bindcraft/settings_target/PDL1.json' --filters '/root/bindcraft/settings_filters/default.json' --advanced '/root/bindcraft/settings_advanced/4stage_multimer.json'
(4) there can be issues with some installation of PyRosetta. If you encounter problems follow the previous suggestion of using the ubuntu wheel.

**Comment by martinpacesa** [comment]
Yes, the sbatch command is only meant for SLURM based cluster systems, since you are presumably running on a single workstation, you should run it using the python command.
