### ISSUE TITLE
Question about over-representation of E,K,F amino acids in sequences

### ISSUE THREAD

**Issue by linuxfold** [martinpacesa/BindCraft#130]
I noticed that there are a lot of E, K, and F in output sequences that pass filters in the preprint paper and in the sequences that I am generating. They are way above natural levels in your average protein. 

Is this expected for some reason? Would there be a benefit to forcing more variability i.e. E->D/Q, K->R, F->W/Y?

It might also be beneficial to reduce the overall charges and stabilize key folds with disulfide bonds.

**Comment by martinpacesa** [comment]
That seems to be a common bias of using soluble MPNN for optimising sequence. If you use vanilla MPNN it will be more biased to AAAA sequences and we found these to be more soluble and more crystallisable. There are ways to tune it but we have not checked what effect that would have

**Comment by linuxfold** [comment]
Interesting. I admittedly don't know enough about how all the individual parts work...

From your preprint:
> we and others14,20 have previously demonstrated that AF2-hallucinated proteins can exhibit low levels of
> expression when tested experimentally have previously demonstrated that AF2-hallucinated proteins can exhibit low levels of expression when tested experimentally. We therefore subsequently optimize the sequence of the binder core and surface using MPNNsol13,20 while keeping the interface intact (Fig. 1a).

The primary purpose of MPNN is just for solubility/expression?

If I were to manually mutate non interface residues to reduce charges or add a disulfide bond and the ipTM score remains the same upon plugging into AF, the chances of it binding, assuming it can be expressed and is soluble, are identical?

**Comment by martinpacesa** [comment]
Yeah, it's to make them stable and expressable. You can try to mutate them, but I cannot say how well that will work. You can also tune the distribution of amino acids but you would have to change the underlying code. 

Yeah those are the main filters
