### ISSUE TITLE
scipy no attribute 'tril' - need specific version

### ISSUE THREAD

**Issue by james-vincent** [martinpacesa/BindCraft#132]
The install script does not specify versions for anything except flax and numpy. This results in scipy 1.13.1 being installed in my case. This version of scipy is too new apparently and no longer includes 'tril':

    @_wraps(scipy.linalg.tril)
AttributeError: module 'scipy.linalg' has no attribute 'tril'

print(scipy.__version__)'
1.13.1

Can you please provide a complete environment.yml file with versions specified from a working install?

**Comment by martinpacesa** [comment]
Scipy should be 1.12.x or lower
