### ISSUE TITLE
Potential feature request

### ISSUE THREAD

**Issue by TimCraigCGPS** [martinpacesa/BindCraft#133]
Hi @martinpacesa - I was wondering if you may have tried this: https://academic.oup.com/bioinformaticsadvances/article/4/1/vbae153/7818424

In your optimization of the AFmultimer section of the pipeline.  Essentially, they reduce the number of models in AF multimer from 5 to 1 without a big drop in accuracy, but getting a 4.something x speedup. If you haven't explored this I might try it.

**Comment by martinpacesa** [comment]
There are two things to address here:
1. Design and prediction with AF are two very different use cases. In the case of prediction with MSAs (the intended use) one model can certainly be enough, though not always. In the case of design you would quickly run into sequence overfitting, i.e. making sequences that one model likes but are not real.

2. At each iteration we only use model at a time so it wouldn't actually be faster.

My prediction is that if you only design and predict with one model your experimental success rates will go down.
