### ISSUE TITLE
Trimmed target flexibility artifacts

### ISSUE THREAD

**Issue by salvatta2** [martinpacesa/BindCraft#134]
Hi, congrats for this excellent method! I have tried a simple design using the Colab version, and I observe that the target structure (which I have trimmed to leave only 2 discontinuous peptide epitopes, following the advice of #56 and #90) is significantly modified in the output results. I guess the issue is that too much trimming will expose hydrophobics and these are artefactually folded. 

See attached the input PDB. Is there a recommended way to keep the backbone conformation of the target fixed?
[trim.pdb.txt](https://github.com/user-attachments/files/18139927/trim.pdb.txt)

Thanks!

**Comment by martinpacesa** [comment]
Hi, unfortunately not right now, I would recommend adding more contxt of the protein if possible.

**Comment by salvatta2** [comment]
I see, thanks, will do as suggested!
