### ISSUE TITLE
Colab fail: Cannot open file after step 4

### ISSUE THREAD

**Issue by bifxcore** [martinpacesa/BindCraft#136]
Hello Martin,

Jobs on Colab are crashing after successfully completing Step4 (see stacktrace below).
Colab complains about not being able to open a file, but I can navigate to that file from the Colab notebook left-hand menu.

Here's the stack trace:

Trajectory successful, final pLDDT: 0.83
Starting trajectory took: 0 hours, 4 minutes, 6 seconds

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-11-8a2960c70177>](https://localhost:8080/#) in <cell line: 18>()
     72             # Relax binder to calculate statistics
     73             trajectory_relaxed = os.path.join(design_paths["Trajectory/Relaxed"], design_name + ".pdb")
---> 74             pr_relax(trajectory_pdb, trajectory_relaxed)
     75 
     76             # define binder chain, placeholder in case multi-chain parsing in ColabDesign gets changed

1 frames
[/usr/local/lib/python3.10/dist-packages/pyrosetta/io/__init__.py](https://localhost:8080/#) in pose_from_pdb(filename)
     18 # because otherwise, it wrecks a lot of people's scripts.  ~Labonte
     19 def pose_from_pdb(filename):
---> 20     return pose_from_file(filename)
     21 
     22 

RuntimeError: 

File: /home/benchmark/rosetta/source/src/core/import_pose/import_pose.cc:361
[ ERROR ] UtilityExitException
ERROR: Cannot open file "path to my file"

where "path to my file" is the correct path to the actual file, e.g. "/content/drive/My Drive/Colab_Notebooks/etc..."

Is it possible that it chokes on the space in 'My Drive' ?

**Comment by bifxcore** [comment]
OK something is wrong:
It's trying to open /content/drive/My Drive/...
but the actual path is /content/drive/MyDrive/...

**Comment by bifxcore** [comment]
This is confusing... On my Google Drive, the directory name is "My Drive", but the actual path from the Notebook is "MyDrive" without the space.

**Comment by McGruffff** [comment]
I think it is okay... I still can see my outputs after what you are saying happened.
