### ISSUE TITLE
rerank the results from two separate executions

### ISSUE THREAD

**Issue by Yu-pecs** [martinpacesa/BindCraft#137]
Hello, I have obtained hundreds of results by running different hotspots and sequence lengths separately. Now I want to put these results together and sort them, how should I proceed?

**Comment by martinpacesa** [comment]
Copy the .pdb files from Accepted folder into one and then merge also the entries in the csv files. Then run the pipeline again without increasing the number of final designs. If it sees there is the desired number of designs in the Accepted folder it just reranks it
