### ISSUE TITLE
DAlphaBall.gcc cannot find libgfortran.so.5

### ISSUE THREAD

**Issue by dshammers** [martinpacesa/BindCraft#139]
The program was running find for several hours then failed and gave the error in the title. I've no idea what it means.

![image](https://github.com/user-attachments/assets/dde6cc85-3390-48ea-b2cb-6f153743c1ed)

**Comment by r-karimi** [comment]
I also had this issue on my machine and solved it by installing the missing library: 
`sudo apt-get install libgfortran5`

**Comment by dshammers** [comment]
> I also had this issue on my machine and solved it by installing the missing library: 
> `sudo apt-get install libgfortran5`


I arrived at the same solution. Thanks for confirming it for me.
