### ISSUE TITLE
af_params_dir in settings_advanced

### ISSUE THREAD

**Issue by komatsuna-san** [martinpacesa/BindCraft#14]
As a test, I added `"af_params_dir": "/path/to/params"` to `4stage_multimer.json` in an attempt to make the `AF weights` located in any directory recognizable. 
However, I received the following warning and the job did not execute. (It works normally when I place `params` within the repository and run `bindcraft.py` inside the repository.)

```log
Starting trajectory: PDL1_l116_s500265
WARNING: 'model_1_multimer_v3' not found
WARNING: 'model_2_multimer_v3' not found
WARNING: 'model_3_multimer_v3' not found
WARNING: 'model_4_multimer_v3' not found
WARNING: 'model_5_multimer_v3' not found
```

Has anyone managed to get this setting to function properly?

**Comment by martinpacesa** [comment]
Yeah, the path actually needs to point to the **parent** directory of params, so in that case it would be `/path/to/`
