### ISSUE TITLE
Bindcraft 1.5.0 add_cyclic_offset function referenced but missing in colabdesign_utils.py

### ISSUE THREAD

**Issue by mar4mn** [martinpacesa/BindCraft#144]
Hi! Great work on BindCraft and version 1.5.0!
I noticed that `add_cyclic_offset` is referenced but missing in `colabdesign_utils.py`.
To resolve the issue, I added the function locally based on its implementation in the ColabDesign repository, and the affected feature ("cyclize_peptide": true) now works as expected (or at least no crashes when running it).
Could you clarify if the omission of this function was an oversight or is it intended as a feature for a future version? I didn’t see any mention of it in the patch notes for version 1.5.0.
Thank you!

**Comment by martinpacesa** [comment]
Hi, please replace the file with the newly updated function, this has now been fixed
