### ISSUE TITLE
I tried using the pipeline for my design however, I am encountering this error

### ISSUE THREAD

**Issue by zarbuk** [martinpacesa/BindCraft#18]
I am getting similar issue of floating point error and tried the methods stated but it isnt working. I am also getting this issue:
dash 2.15.0 requires requests, which is not installed.
flask 3.0.2 requires click>=8.1.3, which is not installed.
flask 3.0.2 requires Jinja2>=3.1.2, which is not installed.
ipython 8.18.1 requires decorator, which is not installed.

**Comment by zarbuk** [comment]
The problem is numpy version 2.0 isnt compatible either

**Comment by finexzhi** [comment]
For any modules are missing, you can easily use ChatGPT to ask "install dash 2.15.0 to Ubuntu/Linux (for example)'. You will be instructed to install the required modules.
