### ISSUE TITLE
Environment installed successfully but "No module named 'numpy' error when running script

### ISSUE THREAD

**Issue by nfloquet** [martinpacesa/BindCraft#19]
hello, after having successfully created the conda env, i get the following message when trying to run the pipeline :+1: 
Traceback (most recent call last):
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/functions/__init__.py", line 6, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

after manually installing it in the environnement, got the same for pandas, matplotlib and pyrosetta. But for pyrosetta got : 
ERROR: Could not find a version that satisfies the requirement pyrosetta (from versions: none)
ERROR: No matching distribution found for pyrosetta

Thank you in advance for your help

**Comment by ajasja** [comment]
It looks like your conda env was not successfully set up. Did you activate the env before running the script? If you run `conda activate BindCraft` and `conda list` you should get the list of installed packages.

**Comment by nfloquet** [comment]
seems to work (but without sourcing the conda environment, perhaps because i already installed pyrosetta and other dependencies for other tools); got this message : 

Stage 3: running (hard)
121 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 2.52 helix 0.68 pae 0.16 i_pae 0.13 con 1.61 i_con 1.93 plddt 0.92 ptm 0.83 i_ptm 0.77
122 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 2.51 helix 0.67 pae 0.16 i_pae 0.13 con 1.60 i_con 1.91 plddt 0.91 ptm 0.83 i_ptm 0.77
123 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 2.51 helix 0.68 pae 0.16 i_pae 0.13 con 1.58 i_con 1.93 plddt 0.92 ptm 0.84 i_ptm 0.77
124 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 2.51 helix 0.68 pae 0.16 i_pae 0.13 con 1.62 i_con 1.88 plddt 0.91 ptm 0.84 i_ptm 0.78
125 models [0, 1, 2, 3, 4] recycles 1 hard 1 soft 1 temp 0.01 loss 2.51 helix 0.67 pae 0.16 i_pae 0.13 con 1.60 i_con 1.91 plddt 0.91 ptm 0.83 i_ptm 0.77
Traceback (most recent call last):
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/bindcraft.py", line 108, in <module>
    trajectory = binder_hallucination(design_name, target_settings["starting_pdb"], target_settings["chains"],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/functions/colabdesign_utils.py", line 202, in binder_hallucination
    binder_contacts = hotspot_residues(model_pdb_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/functions/biopython_utils.py", line 158, in hotspot_residues
    aa_single_letter = Polypeptide.three_to_one(binder_resname)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'Bio.PDB.Polypeptide' has no attribute 'three_to_one'. Did you mean: 'three_to_index'?


*************************
when i source the bindcraft env : got : 
ython bindcraft.py --settings ./settings_target/test.json --filters ./settings_filters/default_filters.json --advanced ./settings_advanced/4stage_multimer_peptides.json 
Traceback (most recent call last):
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/functions/__init__.py", line 11, in <module>
    from .pyrosetta_utils import *
  File "/home/nicolas/PROGRAMMES/BINDCRAFT/BindCraft/functions/pyrosetta_utils.py", line 6, in <module>
    import pyrosetta as pr
ModuleNotFoundError: No module named 'pyrosetta'

**Comment by martinpacesa** [comment]
`AttributeError: module 'Bio.PDB.Polypeptide' has no attribute 'three_to_one'. Did you mean: 'three_to_index'?`

You need to downgrade to biopython 1.79 or 1.78

**Comment by finexzhi** [comment]
Try to re-install PyRosetta following the below steps.

Step 1: Install Dependencies
Before installing PyRosetta, ensure you have Python and pip installed. PyRosetta supports Python versions 3.6 to 3.9.

Install Python: Download and install Python from [python.org](https://www.python.org/downloads/). Make sure to check the box to add Python to your PATH during installation.
Install pip: Pip usually comes with Python, but you can ensure it's installed by running:
bash
Copy code
python -m ensurepip --upgrade
Step 2: Download PyRosetta
You can obtain the PyRosetta package from the official PyRosetta website or GitHub repository. If you have access to the PyRosetta repository, follow the instructions there.

Step 3: Install PyRosetta
You can typically install PyRosetta using pip. If you have a precompiled wheel file for PyRosetta:

Navigate to the directory where the wheel file is located.
Run the following command (replace pyrosetta.whl with the actual file name):
bash
Copy code
pip install pyrosetta.whl
If you're installing from source or using the GitHub repository:

Clone the repository (if applicable):
bash
Copy code
git clone https://github.com/sqzpp/pyrosetta.git
cd pyrosetta
Install using pip:
bash
Copy code
pip install .
Step 4: Verify the Installation
To ensure PyRosetta is installed correctly, you can open a Python interpreter and run:

python
Copy code
import pyrosetta
pyrosetta.init()
If there are no errors, the installation was successful!

**Comment by nfloquet** [comment]
thanks it works now
