### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by ajasja** [martinpacesa/BindCraft#2]
The default install script works surprisingly well!

However when running the script we get:

`Floating point exception (core dumped)`
![image](https://github.com/user-attachments/assets/1076fb82-046f-4983-a9a3-dd279468024d)

We do have a cuda graphics card, so I'm not sure where the problem is:
![image](https://github.com/user-attachments/assets/bb156cd6-b8b0-45f5-9917-4ef45559fff3)

**Comment by ajasja** [comment]
With a couple of print statements I've narrowed it down to `pyrosetta_utils`.

**Comment by martinpacesa** [comment]
This seems to be a PyRosetta problem. Which version do you have? Can you try to unisntall the pip version and try to install the conda version?

**Comment by martinpacesa** [comment]
Are you running numpy 2?

**Comment by martinpacesa** [comment]
> This seems to be a PyRosetta problem. Which version do you have? Can you try to unisntall the pip version and try to install the conda version?

Sorry, I meant other way around, try the pip install

**Comment by ajasja** [comment]
Whatever the install script installed. 
pyrosetta                 2024.39+release.59628fb          py39_0    https://conda.graylab.jhu.edu
numpy                     1.26.4           py39heeff2f4_0  

Seems strange on two accounts -- there is nothing in the import statements that runs any code (maybe I missed something).

And in an ipython session pyrosetta init works well
![image](https://github.com/user-attachments/assets/2b1c2cdf-43a1-4a3a-ba26-2a0d0839b903)

Will try to mess around, a bit and try the pip version.

**Comment by martinpacesa** [comment]
what if you run `conda install pyrosetta=2024.24+release.ca096da=py39_0 --channel https://levinthal:paradox@conda.graylab.jhu.edu`

**Comment by Jojo109x** [comment]
I had the same error. Installing the ubuntu wheel fixed it.

**Comment by sokrypton** [comment]
> I had the same error. Installing the ubuntu wheel fixed it.

can you share how you did this?

**Comment by manifoldmike** [comment]
I believe the Floating point exception occurs during the import jax statement in the generic_utils.py script in functions.

**Comment by gha2012** [comment]
Thanks so much for sharing this! Same problem here:
`Running the BindCraft pipeline
Running binder design for target /home/mhoe/bindcraft/BindCraft/settings_target/PDL1.json
Design settings used: /home/mhoe/bindcraft/BindCraft/settings_advanced/4stage_multimer.json
Filtering designs based on /home/mhoe/bindcraft/BindCraft/settings_filters/default_filters.json
/var/lib/slurm/slurmd/job01683/slurm_script: line 32: 833689 Floating point exception(core dumped) python -u ./bindcraft.py --settings "${SETTINGS}" --filters "${FILTERS}" --advanced "${ADVANCED}"`

**Comment by martinpacesa** [comment]
Could you try downgrading your pyrosetta using this command? `conda install pyrosetta=2024.24+release.ca096da=py39_0 --channel https://levinthal:paradox@conda.graylab.jhu.edu`

This problem seems to be system specific and we don't encounter it on our setup, nor in the colab, so it's a bit difficult to debug

**Comment by Jojo109x** [comment]
> > I had the same error. Installing the ubuntu wheel fixed it.
> 
> can you share how you did this?

Sure!

1) I installed the conda environment following the instructions (including the original suggestion for pyrosetta)
2) activated the environment (conda activate BindCraft)
3) Manually deleted the original pyrosetta (pip uninstall pyrosetta)
4) Downloaded a suitable wheel file from https://graylab.jhu.edu/download/PyRosetta4/archive/release/

In my case since I am using Ubuntu and python 3.9, pyrosetta-2024.24+release.ca096dac4f-cp39-cp39-linux_x86_64.whl seemed good (https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/)

5) While having the environment active, I installed pyrosetta from the wheel file (pip install ~/Download/*wheel_file*)

**Comment by noguhiro2002** [comment]
My environment is Ubuntu 22.04. Thank you very much, Jojo109x. Your method works for my computer :)

**Comment by lyskov** [comment]
Re PyRosetta install using wheels: there is no need to do this by-hands. Instead i would recommend to try using our pyrosetta-installer package:
```bash
pip install pyrosetta-installer 
python -c 'import pyrosetta_installer; pyrosetta_installer.install_pyrosetta()'
```
Re Issues with Conda version: segfault during imports in conjunction with Jax package is most likely issue with Pybind11/C++-type-id conflicts. Possible workaround would be to try reverse import order, use different PyRosetta or Jax version (suggested workaround with using Ubuntu wheels).

(also note that Conda PyRosetta package build with threads+serialization support so more C++ std types are bound there)

**Comment by ajasja** [comment]
@lyskov method does not work, since we get `pyrosetta-2024.39+release.59628fb.dist-info`, which does not seem to work.
I can confirm that pyrosetta-2024.24+release.ca096dac4f-cp39-cp39-linux_x86_64.whl runs!

**Comment by martinpacesa** [comment]
Excellent! You install it from the conda repo?
`conda install pyrosetta=2024.24+release.ca096da=py39_0 --channel https://conda.graylab.jhu.edu`

**Comment by dominik-handler** [comment]
Hi, 

for me this solution did not work. I created a completely fresh installation according to the install script and replaced the pyrosetta install with the command you suggested. I still get the Floating Point exception.

> Excellent! You install it from the conda repo? `conda install pyrosetta=2024.24+release.ca096da=py39_0 --channel https://conda.graylab.jhu.edu`

**Comment by martinpacesa** [comment]
Could you let me know whether it works or not and your:

- pyrosetta version
- GCC version
- numpy version
- python version

**Comment by dominik-handler** [comment]
Python 3.9.19
numpy 1.26.4
gcc (GCC) 11.2.0
pyrosetta 2024.24+release.ca096da

**Comment by martinpacesa** [comment]
the incompatibility seems to stem from PyRosetta and Jax installation.

**Comment by ajasja** [comment]
@martinpacesa I downloaded the wheel and installed it manually using `pip install /path/to/wheel`

**Comment by ajasja** [comment]
With
```
conda install biopython==1.79 numpy matplotlib scipy"<1.13.0" pdbfixer seaborn tqdm jupyter ffmpeg chex dm-haiku dm-tree joblib ml-collections immutabledict optax jaxlib=*=*cuda11* jax cuda-nvcc flax pyrosetta -c anaconda -c conda-forge -c nvidia --channel https://conda.graylab.jhu.edu/ 
```
I Get 
```
Could not solve for environment specs
The following package could not be installed
└─ jaxlib * *cuda11* is not installable because it requires
   └─ __cuda, which is missing on the system.
```

**Comment by esendinc** [comment]
> > > I had the same error. Installing the ubuntu wheel fixed it.
> > 
> > 
> > can you share how you did this?
> 
> Sure!
> 
> 1. I installed the conda environment following the instructions (including the original suggestion for pyrosetta)
> 2. activated the environment (conda activate BindCraft)
> 3. Manually deleted the original pyrosetta (pip uninstall pyrosetta)
> 4. Downloaded a suitable wheel file from https://graylab.jhu.edu/download/PyRosetta4/archive/release/
> 
> In my case since I am using Ubuntu and python 3.9, pyrosetta-2024.24+release.ca096dac4f-cp39-cp39-linux_x86_64.whl seemed good (https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/)
> 
> 5. While having the environment active, I installed pyrosetta from the wheel file (pip install ~/Download/_wheel_file_)

Which PyRosetta would you recommend for Linux? I tried two (pyrosetta-2024.24+release.ca096da-cp39-cp39-linux_x86_64.whl and pyrosetta-2024.39+release.59628fb-cp39-cp39-linux_x86_64.whl), but I still got the same floating point exception error (with Python 3.9.19 and gcc (GCC) 4.8.5 20150623 and numpy 1.24.3)

**Comment by coreyhowe999** [comment]
The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:

```
git clone -q https://github.com/martinpacesa/BindCraft
cd BindCraft
bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
conda activate BindCraft
wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
pip uninstall pyrosetta -y
pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
pip install --force-reinstall jax
python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
```

**Comment by martinpacesa** [comment]
@lyskov is working on a PyRosetta update that hopefully addresses this incompatibility

**Comment by zarbuk** [comment]
> conda install pyrosetta=2024.24+release.ca096da=py39_0 --channel https://conda.graylab.jhu.edu

I tried it, it dint work 
run: error: gpu001: task 0: Floating point exception (core dumped)

**Comment by zarbuk** [comment]
> what if you run `conda install pyrosetta=2024.24+release.ca096da=py39_0 --channel https://conda.graylab.jhu.edu` Maybe there is some inconsistency in the newest PyRosetta version. Kiarash Jamali fixed it by installing the ubuntu wheel
> 
> Indeed, it could be a problem with the **Linux distribution**. The Colab version also runs on the ubuntu wheel and doesn't have this problem.

How do we overcome that in linux distribution system?

**Comment by zarbuk** [comment]
> pyrosetta-2024.24+release.ca096dac4f-cp39-cp39-linux_x86_64.whl

I have the same version , still I am getting the error. Can you please tell me how did you fix it?

**Comment by zarbuk** [comment]
I tried this too nad here is what I get:
Jax plugin configuration error: Exception when calling jax_plugins.xla_cuda12.initialize()
Traceback (most recent call last):
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/jax/_src/xla_bridge.py", line 328, in discover_pjrt_plugins
    plugin_module.initialize()
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/jax_plugins/xla_cuda12/__init__.py", line 78, in initialize
    options = xla_client.generate_pjrt_gpu_plugin_options()
AttributeError: module 'jaxlib.xla_client' has no attribute 'generate_pjrt_gpu_plugin_options'
Traceback (most recent call last):
  File "/home/zbukhari/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/net/clusterhn.cluster.pssclabs.com/home/zbukhari/BindCraft/functions/__init__.py", line 12, in <module>
    from .colabdesign_utils import *
  File "/net/clusterhn.cluster.pssclabs.com/home/zbukhari/BindCraft/functions/colabdesign_utils.py", line 11, in <module>
    from colabdesign import mk_afdesign_model, clear_mem
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/__init__.py", line 10, in <module>
    from colabdesign.af.model import mk_af_model
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/model.py", line 7, in <module>
    from colabdesign.af.alphafold.model import data, config, model, all_atom
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/data.py", line 20, in <modu$
    from colabdesign.af.alphafold.model import utils
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/utils.py", line 23, in <mod$
    import haiku as hk
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/__init__.py", line 55, in <module>
    from haiku.experimental import flax
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/flax.py", line 18, in <module>
    from haiku._src.flax.flax_module import Module
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/_src/flax/flax_module.py", line 20, in <module>
    import flax.core
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/__init__.py", line 24, in <module>

from colabdesign.af.model import mk_af_model
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/model.py", line 7, in <module>
    from colabdesign.af.alphafold.model import data, config, model, all_atom
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/data.py", line 20, in <modu$
    from colabdesign.af.alphafold.model import utils
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/colabdesign/af/alphafold/model/utils.py", line 23, in <mod$
    import haiku as hk
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/__init__.py", line 55, in <module>
    from haiku.experimental import flax
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/experimental/flax.py", line 18, in <module>
    from haiku._src.flax.flax_module import Module
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/haiku/_src/flax/flax_module.py", line 20, in <module>
    import flax.core
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/__init__.py", line 24, in <module>
    from flax import core
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/core/__init__.py", line 15, in <module>
    from .axes_scan import broadcast as broadcast
  File "/home/zbukhari/miniconda3/envs/BindCraft/lib/python3.9/site-packages/flax/core/axes_scan.py", line 41, in <module>
    length: int | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
srun: error: gpu001: task 0: Exited with exit code 1

**Comment by ajasja** [comment]
@zarbuk Try to install through pip. If you get the `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'` error, you have solved the core dumped problem :) And you can try downgrading jax to 0.4.23 https://github.com/martinpacesa/BindCraft/issues/5

**Comment by lyskov** [comment]
> @lyskov method does not work, since we get `pyrosetta-2024.39+release.59628fb.dist-info`, which does not seem to work.
> I can confirm that pyrosetta-2024.24+release.ca096dac4f-cp39-cp39-linux_x86_64.whl runs!

@ajasja could you please elaborate on this? Do you mean that installer tries to use non-wheel-file/try-to-download-non-existent-wheel? Or is it getting the wheel but that wheel does not work? Thanks,

**Comment by zarbuk** [comment]
> @zarbuk Try to install through pip. If you get the `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'` error, you have solved the core dumped problem :) And you can try downgrading jax to 0.4.23 #5

I tried using pip, I still get the same error of core dumped

**Comment by yunong782** [comment]
> The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> 
> ```
> git clone -q https://github.com/martinpacesa/BindCraft
> cd BindCraft
> bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> conda activate BindCraft
> wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip uninstall pyrosetta -y
> pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip install --force-reinstall jax
> python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> ```

this also worked for us and figured out the problems

**Comment by zarbuk** [comment]
> The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> 
> ```
> git clone -q https://github.com/martinpacesa/BindCraft
> cd BindCraft
> bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> conda activate BindCraft
> wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip uninstall pyrosetta -y
> pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip install --force-reinstall jax
> python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> ```

I tried this it eliminate the core dump issue but the int type issue persist

**Comment by zarbuk** [comment]
> > The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> > ```
> > git clone -q https://github.com/martinpacesa/BindCraft
> > cd BindCraft
> > bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> > conda activate BindCraft
> > wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> > pip uninstall pyrosetta -y
> > pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> > pip install --force-reinstall jax
> > python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> > ```
> 
> this also worked for us and figured out the problems

are you using Linux distribution system?

**Comment by zarbuk** [comment]
I get type nas none type error when using this...

**Comment by dominik-handler** [comment]
I finally managed to package BindCraft into a Apptainer container that runs successfully. 
You can download the built container using:
`wget https://brenneckelab.imba.oeaw.ac.at/tmp/BindCraft.app`

To execute it you can run it as:
`apptainer run --containall --contain --nv BindCraft.app --settings /path/setting.json
`

Feel free to take and adopt/modify the definition file to your needs:
```
#BindCraft in Apptainer
Bootstrap: docker
From: mambaorg/micromamba:jammy

%labels
  BindCraft Apptainer by Dominik Handler <Dominik Handler@imba.oeaw.ac.at>
  GitHub/GitLab: dominik-handler

%runscript
    X="$@"
    export X

    bash -c '
      source /usr/local/bin/_activate_current_env.sh
      cd /BindCraft 

      python -u /BindCraft/bindcraft.py $X
    '

%post
  SHELL=/bin/bash
  export SHELL

  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake git  wget curl gfortran

  cd /
  
  git clone https://github.com/martinpacesa/BindCraft 
  cd /BindCraft

  micromamba config append channels conda-forge
  micromamba config append channels bioconda
  micromamba config append channels defaults

  bash -c '
    source /usr/local/bin/_activate_current_env.sh  
    micromamba install python=3.9 numpy"<2" -y

    cd /BindCraft
    install_dir=$(pwd)

    micromamba install biopython==1.79 scipy"<1.13.0" pdbfixer seaborn tqdm jupyter ffmpeg -y
    pip install matplotlib==3.7.1

    pip install git+https://github.com/sokrypton/ColabDesign.git

    wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
    pip uninstall pyrosetta -y
    pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl

    pip install --force-reinstall "jax[cuda12]" numpy"<2"

    # chmod executables
    chmod +x ${install_dir}/functions/dssp
    chmod +x ${install_dir}/functions/DAlphaBall.gcc

    mkdir -p ${install_dir}/params/
    cd ${install_dir}/params/
    wget -P ${install_dir}/params/ https://storage.googleapis.com/alphafold/alphafold_params_2022-12-06.tar
    tar -xvf ${install_dir}/params/alphafold_params_2022-12-06.tar
    rm ${install_dir}/params/alphafold_params_2022-12-06.tar

    printf "Cleaning up micromamba temporary files to save space\n"
    micromamba clean -a -y
    printf "micromamba cleaned up\n"
'

%environment

%test
```

**Comment by kyleford8** [comment]
> The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> 
> ```
> git clone -q https://github.com/martinpacesa/BindCraft
> cd BindCraft
> bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> conda activate BindCraft
> wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip uninstall pyrosetta -y
> pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip install --force-reinstall jax
> python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> ```


One note on this issue: I followed the above solution, which then led to a numpy1.0 v 2.0 module issue.

 "module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'."

downgrading to numpy 1.26.4 allowed the pipeline to run. 

It did throw a seemingly jax related error, but this did not prevent running:

"The NVIDIA driver's CUDA version is 12.4 which is older than the ptxas CUDA version (12.6.77). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages."

I'm running on google compute, g2-standard-8 with L4 GPU.

**Comment by zarbuk** [comment]
> > The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> > ```
> > git clone -q https://github.com/martinpacesa/BindCraft
> > cd BindCraft
> > bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> > conda activate BindCraft
> > wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> > pip uninstall pyrosetta -y
> > pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> > pip install --force-reinstall jax
> > python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> > ```
> 
> One note on this issue: I followed the above solution, which then led to a numpy1.0 v 2.0 module issue.
> 
> "module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'."
> 
> downgrading to numpy 1.26.4 allowed the pipeline to run.
> 
> It did throw a seemingly jax related error, but this did not prevent running:
> 
> "The NVIDIA driver's CUDA version is 12.4 which is older than the ptxas CUDA version (12.6.77). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages."
> 
> I'm running on google compute, g2-standard-8 with L4 GPU.

I got this error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dash 2.15.0 requires requests, which is not installed.
dash 2.15.0 requires typing-extensions>=4.1.1, which is not installed.
flask 3.0.2 requires click>=8.1.3, which is not installed.
flask 3.0.2 requires Jinja2>=3.1.2, which is not installed.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.0.2 which is incompatible.

 Despite that I went go ahead:

Successfully installed importlib-metadata-8.5.0 jax-0.4.30 jaxlib-0.4.30 ml-dtypes-0.5.0 numpy-2.0.2 opt-einsum-3.4.0 scipy-1.13.1 zipp-3.20.2
(BindCraft) [zbukhari@fock BindCraft]$ python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
Traceback (most recent call last):
  File "/home/zbukhari/BindCraft/bindcraft.py", line 5, in <module>
    from functions import *
  File "/home/zbukhari/BindCraft/functions/__init__.py", line 7, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

**Comment by zarbuk** [comment]
> > The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> > ```
> > git clone -q https://github.com/martinpacesa/BindCraft
> > cd BindCraft
> > bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> > conda activate BindCraft
> > wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> > pip uninstall pyrosetta -y
> > pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> > pip install --force-reinstall jax
> > python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> > ```
> 
> One note on this issue: I followed the above solution, which then led to a numpy1.0 v 2.0 module issue.
> 
> "module that was compiled using NumPy 1.x cannot be run in NumPy 2.0.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'."
> 
> downgrading to numpy 1.26.4 allowed the pipeline to run.
> 
> It did throw a seemingly jax related error, but this did not prevent running:
> 
> "The NVIDIA driver's CUDA version is 12.4 which is older than the ptxas CUDA version (12.6.77). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages."
> 
> I'm running on google compute, g2-standard-8 with L4 GPU.

Thanks, this ran for me too nad I got similar error but the designs are running.

**Comment by uioQPS** [comment]
> The below code worked for me on a Nvidia Rapids image hosted on a Paperspace VM:
> 
> ```
> git clone -q https://github.com/martinpacesa/BindCraft
> cd BindCraft
> bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/opt/conda'
> conda activate BindCraft
> wget https://graylab.jhu.edu/download/PyRosetta4/archive/release/PyRosetta4.Release.python39.ubuntu.wheel/pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip uninstall pyrosetta -y
> pip install pyrosetta-2024.38+release.200d5f9a7d-cp39-cp39-linux_x86_64.whl
> pip install --force-reinstall jax
> python -u bindcraft.py --settings 'PDL1.json' --filters 'settings_filters/default_filters.json' --advanced 'settings_advanced/4stage_multimer.json'
> ```

after follow this，I got new wrong message
ImportError: /usr/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/jiawei/anaconda3/envs/BindCraft/lib/python3.9/site-packages/pyrosetta/rosetta.so
how can deal with it？

**Comment by zarbuk** [comment]
Try pip installing it

**Comment by martinpacesa** [comment]
I think a got a combination that works, could someone try this? I ran this without problems on our CUDA12 server, you can change the cuda version to correspond your setup but the main conda command needs to be run as one line :
```
conda create --name BindCraft python=3.10 -y
conda activate BindCraft
CONDA_OVERRIDE_CUDA="12.4" conda install pip pandas matplotlib numpy"<2.0.0" biopython scipy pdbfixer seaborn tqdm jupyter ffmpeg pyrosetta fsspec py3dmol chex dm-haiku dm-tree joblib ml-collections immutabledict optax jaxlib=*=*cuda* jax cuda-nvcc cudnn -c conda-forge -c anaconda -c nvidia  --channel https://conda.graylab.jhu.edu/ -y
pip3 install git+https://github.com/sokrypton/ColabDesign.git --no-deps
chmod +x ${install_dir}/functions/dssp
chmod +x ${install_dir}/functions/DAlphaBall.gcc
```

**Comment by martinpacesa** [comment]
I updated the repository to reflect the latest changes

**Comment by kyleford8** [comment]
> I updated the repository to reflect the latest changes

Tested this with a fresh install on a CUDA 12 machine and had no issues this time. Thanks for all the hard work here!
