### ISSUE TITLE
GPU Setup

### ISSUE THREAD

**Issue by GoldEagle93** [martinpacesa/BindCraft#21]
What is your recommended hardware to run this? Do we need a single GPU with 32+ GB of memory or can his be parallelized on several GPUs?

**Comment by martinpacesa** [comment]
BindCraft can only use one GPU at a time but of course you can run multiple instances of the pipeline  pointing to the same output folder to "paralelise" it, I wrote it in a way that it doesn't clash. In terms of GPU types, memory allows you to work with bigger targets, 32 Gb will allow you to design for about 500 amino acids of combined target+binder size. 80 Gb will allow for about 900 amino acids.

**Comment by GoldEagle93** [comment]
Thank you. May I ask what GPU you used for testing this. There are very few options with so much memory.

**Comment by martinpacesa** [comment]
We tried on V100, A100, L40s, and H100. Again, you only need so much memory if you want to run this size of complexes, if you trim it and run smaller then it will easily run on 4080s.

**Comment by martinpacesa** [comment]
In theory it also just runs on CPU and RAM but it's very very very slow.
