### ISSUE TITLE
specification of the number of GPUs

### ISSUE THREAD

**Issue by komatsuna-san** [martinpacesa/BindCraft#22]
Is it possible to specify the number of GPUs without using `Slurm` when running `bindcraft.py`?

**Comment by martinpacesa** [comment]
It only runs on 1 GPU at a time but you can run multiple instances of the pipeline in parallel and point to the same output folder to speed it up.

**Comment by finexzhi** [comment]
I am assuming that Slurm can do the parallel computation.

**Comment by martinpacesa** [comment]
You can use slurm to launch multiple jobs. You can also just open multiple command line instances and run the python if you have multiple GPUs.
