### ISSUE TITLE
Binders binding to the cell membrane internal chains

### ISSUE THREAD

**Issue by dionjwa** [martinpacesa/BindCraft#24]
I specify hotspots that are outside the cell membrane part of the target, but the binder seems to be binding mostly to the part of the target that's embedded in the cell membrane. 

Are there config options that would filter those out?

**Comment by finexzhi** [comment]
That is a negative design that I am thinking to avoid the common epitopes and undesirable domains. But still if you increase the design numbers, you should be able to get enough hits to your ECD or extracellular loops.

**Comment by martinpacesa** [comment]
Unfortunately not at this time. The best course of action is to trim the transmembrane segments away from the input .PDB. It will always preferentially bind to the transmembrane regions as they are hydrophobic.
