### ISSUE TITLE
unused config `extract_interfaces`

### ISSUE THREAD

**Issue by pagpires** [martinpacesa/BindCraft#26]
First, thanks for creating this tool!  Very helpful to the community.

My question: `extract_interfaces` seems not used either in BindCraft or in ColabDesign?  From the description, it seems a useful util function

**Comment by martinpacesa** [comment]
Thanks for the catch! This was a feature that was removed for the initial release as it was not performing very consistently for interface analysis, I will reimplement this at a later date.
