### ISSUE TITLE
Colab misses 4stage_multimer_beta.json for beta-sheet option

### ISSUE THREAD

**Issue by QuantitativeVirology** [martinpacesa/BindCraft#27]
Hi Martin,

thanks for the great Colab!

Unfortunately, the colab seems to miss a file for the beta-sheet mode. It throws: FileNotFoundError: [Errno 2] No such file or directory: '/content/bindcraft/settings_advanced/4stage_multimer_beta.json'

Best,

Jens

**Comment by martinpacesa** [comment]
Thank you for the report! I fixed it now
