### ISSUE TITLE
About EGFR

### ISSUE THREAD

**Issue by AIM132** [martinpacesa/BindCraft#28]
Have you ever designed a binder for EGFR and what were the results? Is there any wet experiment verification?Thanks！

**Comment by LennartNickel** [comment]
Yes, its not part of the pre-print, but it has been validated during a design competition:
Please refer to Round 1:
https://design.adaptyvbio.com/

**Comment by AIM132** [comment]
May I ask again how to resolve the following error?Thanks

![bde5f98c8eb97ade2efe568ac46f1f34](https://github.com/user-attachments/assets/1a5106d9-5d52-4b7b-9ca8-865bfa24dd64)

**Comment by martinpacesa** [comment]
which ColabDesign version do you have installed?

**Comment by AIM132** [comment]
![868b617bfa3e800f9331132b0d2a914b](https://github.com/user-attachments/assets/a870dbce-f2e6-4d10-96fa-3a3cf85a3b1f)
1.1.1

**Comment by AIM132** [comment]
I upgraded it to 1.1.2 and now there are no issues. Thank you very much!
