### ISSUE TITLE
Biopython issue with module three_to_one

### ISSUE THREAD

**Issue by GEC-git** [martinpacesa/BindCraft#30]
Hello,

Which version of Biopython should be installed? I am running BindCraft locally and I end up with an attribute error: AttributeError: module 'Bio.PDB.Polypeptide' has no attribute 'three_to_one'

Thanks for the help,
Best
Irene

**Comment by martinpacesa** [comment]
You need version 1.78. I will update the repo next week to work with newer versions of biopython
