### ISSUE TITLE
multiple target chains

### ISSUE THREAD

**Issue by jflucier** [martinpacesa/BindCraft#31]
Hi

for the target_settings json. How can we specifiy multiple chains?

In PDL1 its only 1 chain:

> {
>     "design_path": "/content/drive/My Drive/BindCraft/PDL1/",
>     "binder_name": "PDL1",
>     "starting_pdb": "/content/bindcraft/example/PDL1.pdb",
>     **"chains": "A",**
>     "target_hotspot_residues": "56",
>     "lengths": [65, 150],
>     "number_of_final_designs": 100
> }

If my pdb is a complex, how can I specifiy that my target is chain B, C and D in json file?

Thank you in advance for your help,
JF

**Comment by martinpacesa** [comment]
"chains": "A,B,C,D",

**Comment by jflucier** [comment]
thank you very much for quick response!

**Comment by biochristmas** [comment]
Could you please explain how to configure a hotspot that exists simultaneously on both Chain A and Chain B?
