### ISSUE TITLE
versions of packages

### ISSUE THREAD

**Issue by GEC-git** [martinpacesa/BindCraft#32]
Hello!
I am using BindCraft locally and I am often getting errors due to the version of the different packages needed (I opened an issue about it yesterday and few days ago).
This time the problem comes from mk_mpnn_model (mpnn_model = mk_mpnn_model(backbone_noise=advanced_settings["backbone_noise"], model_name=advanced_settings["model_path"], weights=advanced_settings["mpnn_weights"])
TypeError: __init__() got an unexpected keyword argument 'weights')

In order to avoid to constantly annoy you with these questions, would it be possible to have the versions of all the required packages? I think this might help other users as well.

Thanks and best regards
Irene

**Comment by LennartNickel** [comment]
Absolutely, we will update the install script asap.

**Comment by LennartNickel** [comment]
For your error with the weights argument, please try the upgrade the colabdesign version to 1.1.2 as described here: #28 
Let us know if that helps!
