### ISSUE TITLE
problem in running bindcraft in colab

### ISSUE THREAD

**Issue by Fsoltanmohamadi** [martinpacesa/BindCraft#35]
in starting_pdb part, i add a folder and upload my target protein file in that, but when it comes to the running bindcraft, I keep giving the error: no such file or directory. I don't know what to do also I can't find any json file in my drive though I have followed every steps. Sorry if it's such a silly question
![image](https://github.com/user-attachments/assets/c19d8463-746b-4812-a4c1-ab6250a6d3fd)
![vbnm,](https://github.com/user-attachments/assets/1a637e18-f903-444c-9a4e-f09b8c6d3416)

**Comment by LennartNickel** [comment]
Could it be that the path is not correct? It seems like it does not point to a pdb file?

**Comment by Fsoltanmohamadi** [comment]
> Could it be that the path to the starting pdb is not correct? It seems like it does not point to a pdb file?

it's the exact path of my pdb file(/content/drive/MyDrive/BindCraft/Pkd/Trajectory/PKD1,pdb1b4r.pdb) but the error stand still. Should I have a .json file in my drive just like the file I have after cloning? cause there is no such file not even when I  run the PDL 1

**Comment by martinpacesa** [comment]
maybe try a name without the comma, might be that some part of the code does not like that. Also, in your input you have the extension .ent, not .pdb

**Comment by finexzhi** [comment]
content/drive/MyDrive/BindCraft/Pkd/Trajectory/PKD1,pdb1b4r.pdb

The PDB name also looks bizarre to me. It seems that you have two pdb files.

But you raise a good point: The code is running in the cloud. So we do not have the Json files in our drive.

**Comment by finexzhi** [comment]
I also tried to run a new target in addition to PD-L1. It ran well. 
Try to make everything as simple and consistent as possible. 
For example, the path name, pdb name, the data-saving folder name all the same. Hope it can help!

**Comment by Fsoltanmohamadi** [comment]
> maybe try a name without the comma, might be that some part of the code does not like that. Also, in your input you have the extension .ent, not .pdb

I did but I think there's something else that raises problem

**Comment by Fsoltanmohamadi** [comment]
> content/drive/MyDrive/BindCraft/Pkd/Trajectory/PKD1,pdb1b4r.pdb
> 
> The PDB name also looks bizarre to me. It seems that you have two pdb files.
> 
> New .Json file with target settings has been generated in:/content/bindcraft/settings_target/PDL1.json

Thank you, i'll try agian

**Comment by Fsoltanmohamadi** [comment]
> I also tried to run a new target in addition to PD-L1. It ran well. Try to make everything as simple and consistent as possible. For example, the path name, pdb name, the data-saving folder name all the same. Hope it can help!

I will, hope it works too.

**Comment by Fsoltanmohamadi** [comment]
Thank you everyone for taking time and answering my question. I'm glad to say it was solved. I opened "Mount your Google Drive to save design results" code and opened "bindcraft_google_drive", from there I copied the path of every folder that was needed and it worked.
