### ISSUE TITLE
About "No accepted MPNN designs found for this trajectory"

### ISSUE THREAD

**Issue by FunkyLeea** [martinpacesa/BindCraft#38]
Hello,

I've successfully deployed BindCraft locally and tested generating binders for the PDL1 target. However, after running for about 4 hours, none of the binders passed the screening, and each attempt showed the message, "No accepted MPNN designs found for this trajectory." The same issue occurs when I run it on Colab, unlike in the BindCraft notebook, where binders passing the screening appear quite quickly. Could you please help me understand what might be happening here?

Thank you!

![屏幕截图 2024-10-10 122149](https://github.com/user-attachments/assets/4f561eb6-df70-43d5-9a5e-3a186b9fc63d)

**Comment by martinpacesa** [comment]
How many trajectories did you run in each case? The code for the local install and notebook is identical

**Comment by finexzhi** [comment]
PDL1 is definitely an easier target. I got about 8 hits in 2-3 runs.
For another target, it took me 4-5 hours to get 2 hits.
But luck does play a role here.

**Comment by martinpacesa** [comment]
Or rather what AF2 has learned during training plays a role ;)

**Comment by Fsoltanmohamadi** [comment]
> PDL1 is definitely an easier target. I got about 8 hits in 2-3 runs. For another target, it took me 4-5 hours to get 2 hits. But luck does play a role here.

Did you have "Severe clashes detected, skipping analysis and MPNN optimisation" too? before getting hits?
