### ISSUE TITLE
Is that OK to use AlphaFold generated PDB as a template

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#41]
My target does not have a published PDB. Thus I used AlphaFold to generate a PDB as the template.

However, after I ran the software, I continued to see the buffer error messages:
Buffer 9:
		Size: 1.22GiB
		XLA Label: fusion
		Shape: bf16[4,1130,1130,128]
		==========================

	Buffer 10:
		Size: 623.49MiB
		Operator: op_name="jit(_model)/jit(main)/transpose(jvp(jit(apply)))/jit(apply_fn)/alphafold/alphafold_iteration/evoformer/__layer_stack_no_state/while/body/checkpoint/rematted_computation/extra_msa_stack/triangle_multiplication_outgoing/projection/...a, ah->...h/dot_general[dimension_numbers=(((2,), (0,)), ((), ())) precision=None preferred_element_type=bfloat16]" source_file="/content/colabdesign/af/alphafold/model/common_modules.py" source_line=118
		XLA Label: custom-call
		Shape: bf16[1276900,256]
		==========================

	Buffer 11:
		Size: 623.49MiB
		Operator: op_name="jit(_model)/jit(main)/transpose(jvp(jit(apply)))/jit(apply_fn)/alphafold/alphafold_iteration/evoformer/__layer_stack_no_state/while/body/checkpoint/rematted_computation/extra_msa_stack/triangle_multiplication_outgoing/div" source_file="/content/colabdesign/af/alphafold/model/modules.py" source_line=1038 deduplicated_name="input_transpose_fusion.31"
		XLA Label: fusion
		Shape: bf16[256,1130,1130]
		==========================

	Buffer 12:
		Size: 623.49MiB
		XLA Label: fusion
		Shape: f32[1130,1130,128]
		==========================

	Buffer 13:
		Size: 623.49MiB
		Operator: op_name="jit(_model)/jit(main)/transpose(jvp(jit(apply)))/jit(apply_fn)/alphafold/alphafold_iteration/evoformer/__layer_stack_no_state/while/body/checkpoint/rematted_computation/extra_msa_stack/add" source_file="/content/colabdesign/af/alphafold/model/modules.py" source_line=73
		XLA Label: fusion
		Shape: f32[1130,1130,128]
		==========================

	Buffer 14:
		Size: 623.49MiB
		Operator: op_name="jit(_model)/jit(main)/transpose(jvp(jit(apply)))/jit(apply_fn)/alphafold/alphafold_iteration/evoformer/__layer_stack_no_state_1/while/body/checkpoint/rematted_computation/evoformer_iteration/msa_row_attention_with_pair_bias/feat_2d_norm/feat_2d_norm/jit(_var)/sub" source_file="/usr/local/lib/python3.10/dist-packages/haiku/_src/layer_norm.py" source_line=166
		XLA Label: fusion
		Shape: f32[1130,1130,128]
		==========================

	Buffer 15:
		Size: 623.49MiB
		Entry Parameter Subshape: f32[1130,1130,128]
		==========================

**Comment by martinpacesa** [comment]
How big is the pdb you are inputting in amino acids? It is probably too big for your GPU memory, you may have to try it

**Comment by finexzhi** [comment]
Thanks, Martin. You are giving the right direction to solve this problem.
The protein is about 1000 amino acids. But I have defined the hot spot residues to be the first 100 amino acids.
I thought the software will only take it as a 100-aa-long target. But I could be wrong.

**Comment by martinpacesa** [comment]
It takes the whole pdb you provide as input
