### ISSUE TITLE
Base AF2 filters not passed and OOM

### ISSUE THREAD

**Issue by jflucier** [martinpacesa/BindCraft#43]
Hello,

Trying to get new binder sequences. After a 10hr run, I still dont get Accepted design and it fails with OOM error. I see multiple message in log like this one:

```
Trajectory successful, final pLDDT: 0.75
Starting trajectory took: 1 hours, 35 minutes, 13 seconds

Fixing interface residues: B1,B3,B4,B5,B6,B7,B9,B14,B15,B18,B19,B30,B33,B34,B37,B42,B43,B45,B46,B48,B49,B51,B52,B53,B54,B58,B59,B60,B61,B62,B63,B64,B65,B68,B69,B71,B72,B73,B75,B76
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
Base AF2 filters not passed for bctest_l93_s353310_mpnn1, skipping interface scoring
No accepted MPNN designs found for this trajectory.
Design and validation of trajectory IL2_l93_s353310 took: 0 hours, 9 minutes, 21 seconds

```

The error in log is:
```
Stage 1: Test Logits
2024-10-10 20:52:13.892001: W external/xla/xla/service/hlo_rematerialization.cc:2218] Can't reduce memory use below 29.54GiB (31713951744 b
ytes) by rematerialization; only reduced to 30.12GiB (32346241902 bytes)
2024-10-10 20:53:13.636531: W external/tsl/tsl/framework/bfc_allocator.cc:485] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3
0.13GiB (rounded to 32353028864)requested by op 
2024-10-10 20:53:13.638477: W external/tsl/tsl/framework/bfc_allocator.cc:497] ********_

```
I am running on a A100 GPU with 40Gb ram. I tested using 250Gb node ram allocation. Job details informs me that no more then 22GB of node ram is used and that 30Gb of GPU ram is used at most. 

For the job, I am using default json files for filters and advance parameters (default_filters.json & 4stage_multimer.json). Could help me pinpoint parameters I should try testing out first to get BindCraft to predict new binders sequences.

For the memory error, I have seen that these parameters could help: num_seqs & sample_seq_parallel

But this wont help I think getting rid of `Base AF2 filters not passed ` error.

Thank you very much for your help,
JF

**Comment by jflucier** [comment]
Forgot to mention that I have successfully run the PDL1 example with my install
Thank you again for your help

**Comment by martinpacesa** [comment]
How many trajectories have you sampled? It is recommended to sample at least 200 trajectories, for hard targets more like 2000

**Comment by jflucier** [comment]
If I look at trajectory_stats.csv, there is only 4 trajectory detailled

In PLD1 example there is 126 trajectories defined in that file...

This confirms that something is wrong possibly with my input. I am in putting a pdb in complex with a receptor whereas the example file is a single protein. Could this be the problem?

The complex is composed of 4 chains, where A is the ligand and B,C and D are the target. In json, I specify 
`"chains": "B,C,D" `

and some hotspots based on this complex 
`"target_hotspot_residues": "B20,B88,B91,B92,C123,C126,C129,D42,D44,D45,D62",`

thanks for your awesome support.

**Comment by martinpacesa** [comment]
How big are those three chains together? If they are bigger than 600 amino acids you simply might be running out of GPU memory and might need to trim it

**Comment by jflucier** [comment]
Think you got it... total size is 630 aa

Will try to trim and retry. 

thanks again for your help
