### ISSUE TITLE
Failing due to lack of interface residues for mpnn fixed positions?

### ISSUE THREAD

**Issue by jacknicoludis** [martinpacesa/BindCraft#44]
I had a job fail because I think the fixed_positions is empty. The error I got:

```
Traceback (most recent call last):
  File "bindcraft/BindCraft/bindcraft.py", line 171, in <module>
    mpnn_trajectories = mpnn_gen_sequence(trajectory_pdb, binder_chain, trajectory_interface_residues, advanced_settings)
  File "bindcraft/BindCraft/functions/colabdesign_utils.py", line 357, in mpnn_gen_sequence
    mpnn_model.prep_inputs(pdb_filename=trajectory_pdb, chain=design_chains, fix_pos=fixed_positions, rm_aa=advanced_settings["omit_AAs"])
  File "bindcraft/BindCraftEnv/lib/python3.9/site-packages/colabdesign/mpnn/model.py", line 81, in prep_inputs
    p = prep_pos(fix_pos, **pdb["idx"])["pos"]
  File "bindcraft/BindCraftEnv/lib/python3.9/site-packages/colabdesign/shared/prep.py", line 19, in prep_pos
    if i[0].isalpha():
IndexError: string index out of range
```

And the output for this ended with:
```
Trajectory successful, final pLDDT: 0.82
Starting trajectory took: 0 hours, 42 minutes, 0 seconds

Fixing interface residues: 
```

Is this happening because the predicted model has no interface residues?

**Comment by jacknicoludis** [comment]
Yes, I agree it was unsuccessful, but this is an error causing the process to crash. I would hope that the process would keep going to find a binder

**Comment by finexzhi** [comment]
The error traceback you provided indicates an IndexError: string index out of range, which typically occurs when you attempt to access an index in a string (or list) that does not exist. Let's break down the relevant parts of the traceback:

Error Location: The error occurs in the prep_pos function located in bindcraft/BindCraftEnv/lib/python3.9/site-packages/colabdesign/shared/prep.py, specifically at the line if i[0].isalpha():.

Cause: The variable i seems to be expected to be a non-empty string or list, but it’s likely empty when this line is executed. When you try to access i[0] on an empty string or list, you get an IndexError.

Input to prep_pos: The prep_pos function is called with fix_pos and **pdb["idx"]. If fix_pos is an empty list or contains elements that are not valid (like empty strings), this could lead to the observed error.

How to Troubleshoot:
Check fix_pos: Before the line that causes the error, add a print statement to see what fix_pos contains:

python
Copy code
print(f"fix_pos: {fix_pos}")
Inspect pdb["idx"]: Ensure that the pdb["idx"] dictionary being unpacked has valid values and that they are not leading to an empty list or invalid data being passed to prep_pos.

Add Error Handling: You might want to add a check to see if i is empty before accessing its first element:

python
Copy code
if i and i[0].isalpha():
    # your existing code
Trace Data Flow: Follow the data flow from where fix_pos is defined or modified to see where it might be getting set to an empty or invalid state.

By addressing these areas, you should be able to resolve the IndexError. Let me know if you need further help with specific parts of the code!
