### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yunong782** [martinpacesa/BindCraft#48]
I also had a similar problem with index out of range; my job failed at the beginning to hallucinate and it seemed also the problem of <module> from the line 108 from bindcraft.py script.
'Stage 1: Test Logits
Traceback (most recent call last):
  File "/BindCraft/bindcraft.py", line 108, in <module>
    trajectory = binder_hallucination(design_name, target_settings["starting_pdb"], target_settings["chains"],
  File "/BindCraft/functions/colabdesign_utils.py", line 97, in binder_hallucination
    af_model.design_logits(iters=50, e_soft=0.9, models=design_models, num_models=1, sample_models=advanced_settings["sample_models"], save_best=True)
  File "//BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 354, in design_logits
    self.design(iters, **kwargs)
  File "//BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 348, in design
    self.step(lr_scale=lr_scale, num_recycles=num_recycles,
  File "/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 214, in step
    self.run(num_recycles=num_recycles, num_models=num_models, sample_models=sample_models,
  File "/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 89, in run
    model_nums = self._get_model_nums(num_models, sample_models, models)
  File "/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 71, in _get_model_nums
    ns = [ns[n if isinstance(n,int) else ns_name.index(n)] for n in models]
  File "/BindCraft/lib/python3.9/site-packages/colabdesign/af/design.py", line 71, in <listcomp>
    ns = [ns[n if isinstance(n,int) else ns_name.index(n)] for n in models]
IndexError: list index out of range
'

**Comment by soumadwip** [comment]
I also freshly installed BindCraft. I am stuck at this issue after trying to run the PDL1.json file as a test case. I downgraded to Numpy 1.26.4, have python 3.9.13. Could you help me identify what is the issue?

**Comment by martinpacesa** [comment]
What .pdb are you running it on? It seems there may be more models inside of the .pdb?

**Comment by soumadwip** [comment]
I am using the default PDL1.pdb file that is located in the /examples directory

**Comment by DrJayGB** [comment]
I was also making a test run using PDL1. 
along with the error mentioned by yunong782 I get the following warnings. Are these related?
Starting trajectory: PDL1_l111_s508899
WARNING: 'model_1_multimer_v3' not found
WARNING: 'model_2_multimer_v3' not found
WARNING: 'model_3_multimer_v3' not found
WARNING: 'model_4_multimer_v3' not found
WARNING: 'model_5_multimer_v3' not found

**Comment by martinpacesa** [comment]
yes, can you check that the model files are downloaded in bindcraft/params/?

**Comment by yunong782** [comment]
> yes, can you check that the model files are downloaded in bindcraft/params/?
Yes, all 5 model_multimer_v3 were downloaded here in archive folder. And there were 3 different types of each model, they were **params_model_1.npz**, **params_model_1_multimer_v3.npz** and **params_model_1_ptm.npz**, respectively. Shall I have more steps to utilize them before running script?

**Comment by yunong782** [comment]
> I was also making a test run using PDL1. along with the error mentioned by yunong782 I get the following warnings. Are these related? Starting trajectory: PDL1_l111_s508899 WARNING: 'model_1_multimer_v3' not found WARNING: 'model_2_multimer_v3' not found WARNING: 'model_3_multimer_v3' not found WARNING: 'model_4_multimer_v3' not found WARNING: 'model_5_multimer_v3' not found

>I actually ran successfully for the test PDL1 with the example files, but I falied to run my pdb files after the test. It always failed to begin binder hallucination from what scipt reminded. At first I thought it was my problems of target setting with unacceptable target chains, hotspots. I even changed the input target files, but it turned out to be the same problem with **model_number_multimer_v3 not found** in the script.

**Comment by DrJayGB** [comment]
> yes, can you check that the model files are downloaded in bindcraft/params/?

yes they are in directory home/BindCraft/params
all three versions like yunong782 mentioned

**Comment by martinpacesa** [comment]
Can you try to update with the 1.1.0 files and see if it still occurs?

**Comment by DrJayGB** [comment]
Thanks Martin the previous issue got solved 
But now, there is a new TypeError after Stage 4.
in advanced setting 4stage_multimer.json "mpnn_weights": "soluble",

log:

Stage 4: PSSM Semigreedy Optimisation
Running semigreedy optimization...
126 models [2] recycles 1 hard 1 soft 0 temp 1 loss 4.06 helix 1.01 pae 0.20 i_pae 0.16 con 1.93 i_con 1.68 plddt 0.85 ptm 0.83 i_ptm 0.81 rg 2.14
.
.
.
140 models [1] recycles 1 hard 1 soft 0 temp 1 loss 3.70 helix 0.99 pae 0.16 i_pae 0.13 con 1.66 i_con 1.72 plddt 0.89 ptm 0.84 i_ptm 0.78 rg 1.73
Trajectory successful, final pLDDT: 0.9
Starting trajectory took: 0 hours, 14 minutes, 33 seconds

Traceback (most recent call last):
  File "/home/BindCraft/bindcraft.py", line 172, in <module>
    mpnn_trajectories = mpnn_gen_sequence(trajectory_pdb, binder_chain, trajectory_interface_residues, advanced_settings)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/BindCraft/functions/colabdesign_utils.py", line 345, in mpnn_gen_sequence
    mpnn_model = mk_mpnn_model(backbone_noise=advanced_settings["backbone_noise"], model_name=advanced_settings["model_path"], weights=advanced_settings["mpnn_weights"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: mk_mpnn_model.__init__() got an unexpected keyword argument 'weights'

**Comment by martinpacesa** [comment]
it seems you are running on an older version of colabdesign, update your colabdesign version, the weights paramter got included at v1.1.1.

**Comment by LasseMiddendorf** [comment]
Hey, I'm running into the same issue. I checked that my ColabDesign version is at 1.1.2

**Comment by martinpacesa** [comment]
Try to do a reinstall: `pip3 install --force-reinstall git+https://github.com/sokrypton/ColabDesign.git --no-deps`
