### ISSUE TITLE
Can not open pdb file error in running bindcraft cell

### ISSUE THREAD

**Issue by Fsoltanmohamadi** [martinpacesa/BindCraft#49]
Running the model in Google colab, I faced another error: can not open file (path to the file)/file name.pdb.
Though I can open the pd file in pymol,and, notepad++ with no problem. I downloaded the pd from uniprot. Is there any thing wrong with my file? What should I change?
![IMG_20241014_233802_997](https://github.com/user-attachments/assets/641d0618-5215-42b7-b6ff-f625f573c5ce)
![IMG_20241014_233830_315](https://github.com/user-attachments/assets/558cd22c-5ae7-4c25-8801-d20e74d01c2c)

**Comment by martinpacesa** [comment]
I think the space in your 'My Drive' path is the problem, it should just be MyDrive

**Comment by martinpacesa** [comment]
yeah but did you upload PKD1.pdb to example?

**Comment by Fsoltanmohamadi** [comment]
> yeah but did you upload PKD1.pdb to example?

Yeah, it's already there
![image](https://github.com/user-attachments/assets/c940a5be-6146-475e-8b2e-a4a808fb699d)

**Comment by martinpacesa** [comment]
Yeah but that is on MyDrive and your input pdb is pointing to /content/bindcraft/example/PKD1.pdb, not in your MyDrive

**Comment by Fsoltanmohamadi** [comment]
> Yeah but that is on MyDrive and your input pdb is pointing to /content/bindcraft/example/PKD1.pdb, not in your MyDrive

It's the path I interred in Binder design settings section and that error was showed.
![image](https://github.com/user-attachments/assets/fe35cb4b-e2c5-4afe-a7aa-629b94c18adf)

**Comment by martinpacesa** [comment]
Please try running it again without the space in MyDrive

**Comment by Fsoltanmohamadi** [comment]
> Please try running it again without the space in MyDrive

Thank you for the time you take to answering the questions and also for your patience

**Comment by Fsoltanmohamadi** [comment]
> Please try running it again without the space in MyDrive

One more thing, does the model works efficiently in small peptides(at most 20 amino acids)? Cause when I limit the length to 10,20 aa, most of the pLDDTs are under 0.7

**Comment by martinpacesa** [comment]
yes, we have successfully designed and validated 10-20 aa peptide binders. You should use the peptide settigngs and filters
