### ISSUE TITLE
NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by JMB-Scripts** [martinpacesa/BindCraft#50]
Hi 
I got on the collab version of bindcraft, the following error:

 NameError                                 Traceback (most recent call last)
[<ipython-input-1-cd92709e5f79>](https://localhost:8080/#) in <cell line: 6>()
      4 ####################################
      5 # initialise counters
----> 6 script_start_time = time.time()
      7 trajectory_n = 1
      8 accepted_designs = 0

NameError: name 'time' is not defined

Do yo have any idea how get around 
Cheers
JM

**Comment by martinpacesa** [comment]
Try to run all cells again, it seems like not all functions got imported
