### ISSUE TITLE
Parameters to alter

### ISSUE THREAD

**Issue by sami-chaaban** [martinpacesa/BindCraft#51]
Hello,

I've tried a few targets now and have failed to obtain binders with the default parameters. The PDL1 example works just fine, so it's not the installation as far as I can tell. What parameters would you recommend I play with?

Thanks!

**Comment by martinpacesa** [comment]
How many trajectories did you generate so far? Easy targets require about 200-300 trajectories, while hard targets might require more like 2000-3000/

**Comment by sami-chaaban** [comment]
It's not clear to me how many trajectories it generates or how to specify this. My trajectory_stats.csv has between 18-80 rows.

**Comment by martinpacesa** [comment]
each row is one trajectory. You need to just keep it running longer probably

**Comment by sami-chaaban** [comment]
The script seems to have finished in these cases. Is the workflow to keep re-running or is there a way to specify for it to run longer?

**Comment by martinpacesa** [comment]
Just keep running or run parallel jobs into the same output folder. You can also reduce the acceptance_rate setting so it doesn't stop, or just set it to false

**Comment by sami-chaaban** [comment]
Ok I'll try that, thanks!
