### ISSUE TITLE
GPU MISSING?

### ISSUE THREAD

**Issue by titocali1** [martinpacesa/BindCraft#53]
I have this message, I have installed BindCraft in my Drive
![Screenshot 2024-10-16 alle 09 08 27](https://github.com/user-attachments/assets/e1c167e3-c845-4dfb-8180-b05d95ce038d)

**Comment by martinpacesa** [comment]
You need to run a GPU instance on colab, it seems you only allocated CPU resources

**Comment by titocali1** [comment]
Thanks a lot I will try to run it online then.
