### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by Ava-cmd123** [martinpacesa/BindCraft#58]
I'm running into some issues during the installation. 
My NVIDIA driver version is 12.2. When I set up a Conda environment with Python 3.10, I get an error saying 'GLIBC_2.27' not found, which indicates that my GLIBC version is too low. But when I switch to Python 3.9 in the Conda environment and try to install the corresponding version of PyRosetta, I end up with a "Floating point exception" error. Do you have any ideas on how to fix this? I'd really appreciate your help.

**Comment by martinpacesa** [comment]
Can you try again now with a clean install? A new PyRosetta version was pushed

**Comment by Qweasy2** [comment]
I'm running into similar issues. I tried a clean install, but I keep getting floating point exception with python versions >= 3.9. I tried 3.8, but that runs into type errors with objects not being subscriptable. Are there any ways to get past the floating point exceptions.

**Comment by martinpacesa** [comment]
What kind of jax version are you running? It is quite difficult to get the versions right on certain systems. What if you include "libgcc-ng" as package during the conda install?
