### ISSUE TITLE
After hits, how to do the negative selection?

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#59]
I have two similar proteins A and B. The only difference in sequence is about 4 amino acids. I am trying to get a specific binder recognizing A but not B. I have used the different amino acids in A as hot spots. Finally, I got about 20 hits, which all bind to these "hot spot" amino acids. I want to know if these binders will have no or weak binding to B. What software or algorism I should use to evaluate their binding to B before I jump to the wet lab examination. Thanks.
![image](https://github.com/user-attachments/assets/fabb57be-e579-43c8-a797-2a631dc01dc4)

**Comment by martinpacesa** [comment]
That will be very very hard for BindCraft to differentiate. We have a method for this that is not implemented yet, but that will be published only sometime middle next year.
