### ISSUE TITLE
Remove 'anaconda' channel from install

### ISSUE THREAD

**Issue by james-vincent** [martinpacesa/BindCraft#62]
Using the 'anaconda' channel with conda installs may require a license now, even for academic sites.

The new licensing terms from Anaconda are not fully in place but so far still indicate academic sites may need licensing. Academic sites we work with are starting to halt any use of conda because of this.

https://www.anaconda.com/blog/update-on-anacondas-terms-of-service-for-academia-and-research

Could you rework the install to not use the 'anaconda' or 'defaults' channel?

**Comment by james-vincent** [comment]
As a followup, we prefer [pixi](https://pixi.sh/latest/) over conda/mamba. Here is a pixi.toml for install without specifying cuda version:

```
[project]
name = "BindCraft"
description = "binder design pipeline"
version = "1.1.0"
channels = ["https://conda.graylab.jhu.edu", "conda-forge", "nvidia"]
platforms = ["linux-64"]

[system-requirements]
linux="3.10.0"

[dependencies]
numpy = "<2.0.0"
python = "3.10"
pip = "*"
pandas = "*"
matplotlib = "*"
biopython = "*"
scipy = "*"
pdbfixer = "*"
seaborn = "*"
tqdm = "*"
jupyter = "*"
ffmpeg = "*"
pyrosetta = "*"
fsspec = "*"
py3dmol = "*"
chex = "*"
dm-haiku = "*"
dm-tree = "*"
joblib = "*"
ml-collections = "*"
immutabledict = "*"
optax = "*"
jaxlib = "*"
jax = "*"
cuda-nvcc = "*"
cudnn = "*"
```

**Comment by martinpacesa** [comment]
Good suggestion, will remove in next version
