### ISSUE TITLE
PyRosetta requires a license

### ISSUE THREAD

**Issue by james-vincent** [martinpacesa/BindCraft#63]
PyRosetta requires a license (a Rosetta license) and may require a fee. This should be made clear in the installation instructions since the install script adds pyrosetta.  

Including this under the project MIT license is a bit misleading.

https://els2.comotion.uw.edu/product/pyrosetta

**Comment by finexzhi** [comment]
Unless you want to make it commercial. This is basically for research purposes only.

**Comment by james-vincent** [comment]
Pyrosetta requires a license even for academic users.

**Comment by MoritzErtelt** [comment]
PyRosetta does not require a license for academic users doing research anymore, see the [licensing FAQ](https://rosettacommons.org/software/licensing-faq/l) for more details.
