### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by RhysWG** [martinpacesa/BindCraft#66]
I've installed BindCraft as per the instructions on our lab machine running Ubuntu 22.04 LTS, and everything seemed to go OK (no error messages). However when I run it I get a 'Floating point exception (core dumped)' error.  This doesn't seem to be dependent on the configuration files as a get the error even when I just run python -u bindcraft.py

Any assistance you can give would be greatly appreciated.

All the best,

Rhys

**Comment by RhysWG** [comment]
Thanks for the quick response. I install is 1.1.0 (I also got this error with 1.0.0, so I repeated the install, but it didn't go away)

The CUDA version is: 12.2 
Jax version = 0.4.33

**Comment by martinpacesa** [comment]
Can you try running the commands from the install script manually via command line one by one?
Did you specify the CUDA version during install?

**Comment by RhysWG** [comment]
Looks like BindCraft is running now. It appears the issue was my base conda environment not changing to the BindCraft environment when instructed. An extra round of 'conda deactivate' solved the issue. Thanks for the help. :-)
