### ISSUE TITLE
running BindCraft on modal

### ISSUE THREAD

**Issue by Fsoltanmohamadi** [martinpacesa/BindCraft#67]
considering the fact that running BindCraft takes a lot of time and GPU and I, myself have problem with google Colab GPU limit, I wish I could run it on Modal(it is cooperating with adaptyve bio now and offer 30$ free use). I mean a code just like google Colab that does not require me to download Pyrosetta(3 Gigabytes is headache for me). I tried running BindCraft on modal but still I had to download Pyrosetta

**Comment by martinpacesa** [comment]
Hi, currently PyRosetta is a vital component and we do not plan on replacing it for the time being.
