### ISSUE TITLE
Question: is 3stage design inside 4stage_multimer_peptides.json a typo

### ISSUE THREAD

**Issue by antorsae** [martinpacesa/BindCraft#69]
I do not know enough to determine if this is intentional, but just in case:

```
 grep design_algorithm settings_advanced/4stage_multimer_peptides.json
    "design_algorithm": "3stage",
``` 
Is it intentional?

**Comment by martinpacesa** [comment]
The code is correct, the 3stage seems to work better for peptides. Just gotta change the protocol name
