### ISSUE TITLE
How to set up multiple hotspots located on different chains.

### ISSUE THREAD

**Issue by biochristmas** [martinpacesa/BindCraft#71]
How should we configure the target_settings JSON to include multiple hotspots on both Chain A and Chain B?

{
"design_path": "/content/drive/My Drive/BindCraft/PDL1/",
"binder_name": "PDL1",
"starting_pdb": "/content/bindcraft/example/PDL1.pdb",
"chains": "A",
"target_hotspot_residues": "56",
"lengths": [65, 150],
"number_of_final_designs": 100
}

**Comment by martinpacesa** [comment]
It is described in the readme: "A54,A76,B21,B34" or you can include entire chains as "A,B"

**Comment by gieses** [comment]
@martinpacesa apologies for hijacking! Does this also apply to the designed binder? I have some designs but the orientation of the binder is off, wondering if we can enforce an expected orientation?
