### ISSUE TITLE
Google Colab MPNN Checks

### ISSUE THREAD

**Issue by Rohan14T** [martinpacesa/BindCraft#74]
I was testing a protein on google colab and noticed that when it was going through the MPNN checks at the end of each cycle, instead of testing 10 different sequences it tested the same sequence 10 different times. Is this a new error, because I worked with colab before and it worked properly by testing different sequences. 

Also, I am working with a group that is looking to temporarily use google colab to work with BindCraft while we work on installing it on our servers. We were wondering what GPU would work best with BindCraft on colab and what plan would be the best for running BindCraft (Pro, Pro+, or Pay as you go).

**Comment by martinpacesa** [comment]
Can you show an example that it is testing the same sequence? That should not be the case as there is a check to remove duplicate sequences. They can still differ in like 1 or 2 amino acids, if your binder is short.

Google Pro is usually enough

**Comment by Rohan14T** [comment]
I think it was just the counter not updating properly. Double checking the sequences it was slightly different. 

Thank you
