### ISSUE TITLE
Reading PDB residue numbers vs appearance order in PDB file?

### ISSUE THREAD

**Issue by TimCraigCGPS** [martinpacesa/BindCraft#77]
Hi,
  While picking hotspots for an uploaded pdb file, I came across an error that my picked hotspot residue actually doesn't exist.  I was using a PDB file where I pruned a large number of residues out of the system in order to make Bindcraft run faster.  The original pdb had ~400AA, and the new one had only 124, but those 124 still have the residue numbers from the original PDB file.  

My expected and desired behavior would be to use hotspot choices that are based on residue number in the pdb file rather than their appearance inside the uploaded PDB file.  I'm also not sure if the PDB fetching function has the same issue.

Here's part of the contents of my PDB file used:

> ATOM    598  N   ASP A 115     152.516 115.360  99.807  1.00 85.56           N  
ATOM    599  CA  ASP A 115     151.122 115.004 100.139  1.00 85.56           C  
ATOM    600  C   ASP A 115     150.714 115.453 101.556  1.00 85.56           C  
ATOM    601  O   ASP A 115     149.599 115.925 101.773  1.00 85.56           O  
ATOM    602  CB  ASP A 115     150.927 113.481 100.043  1.00 85.56           C  
ATOM    603  CG  ASP A 115     151.019 112.907  98.624  1.00 85.56           C  
ATOM    604  OD1 ASP A 115     150.553 113.580  97.679  1.00 85.56           O  
ATOM    605  OD2 ASP A 115     151.529 111.774  98.515  1.00 85.56           O1-
ATOM    606  H   ASP A 115     153.049 114.680  99.284  1.00 85.56           H  
ATOM    607  HA  ASP A 115     150.453 115.486  99.425  1.00 85.56           H  
ATOM    608  HB2 ASP A 115     149.939 113.237 100.431  1.00 85.56           H  
ATOM    609  HB3 ASP A 115     151.662 112.991 100.682  1.00 85.56           H  

Here is the hotspot from my JSON file:
> "hotspot":"A115,A185,A186,A187,A188,A189,A190,A349"

And here is the error when I run Bindcraft:
>[2024-10-24, 12:18:23 EDT] {EPI_bindcraft.py:127} INFO - AssertionError: ERROR: positions 115 and chain A not found

Is it possible to somehow change the pdb handling to match the PDB numbering more seamlessly?

**Comment by martinpacesa** [comment]
It should match the PDB numbering, so this is a bit strange. How did you do the trimming? Could you try to trim it again, for example in PyMOL or ChimeraX, save and try again?

**Comment by TimCraigCGPS** [comment]
I did it using pymol and "remove atoms" - I wonder if a partial AA would cause this...

**Comment by martinpacesa** [comment]
most likely! I usually remove either in ChimeraX or manually via editing the .pdb file

**Comment by TimCraigCGPS** [comment]
I removed the partial residues, which seems to fix the problem.  Thanks!
