### ISSUE TITLE
shutil.copy(best_model_pdb, design_paths["Rejected"])

### ISSUE THREAD

**Issue by EHHDD2024** [martinpacesa/BindCraft#78]
I got this error message after running my program. What could be causing it, and how should I fix it? Really looking forward to your help!

Fixing interface residues: B43,B63,B66,B69,B70,B73,B74,B77,B78,B80,B81,B82,B85
Base AF2 filters not passed for /home/BindCraft/example/PDL1_l91_s345674_mpnn1, skipping interface scoring
Unmet filter conditions for /home/BindCraft/example/PDL1_l91_s345674_mpnn2
Traceback (most recent call last):
  File "/home/BindCraft/./bindcraft.py", line 411, in <module>
    shutil.copy(best_model_pdb, design_paths["Rejected"])
  File "/home/anaconda3/envs/BindCraft/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/anaconda3/envs/BindCraft/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/BindCraft/example/PDL1_l91_s345674_mpnn2_model2.pdb'

**Comment by martinpacesa** [comment]
Try updating the bindcraft.py file from the latest repo now.

**Comment by EHHDD2024** [comment]
> 现在尝试从最新的 repo 更新 bindcraft.py 文件。
Thank you so much! After updating bindcraft.py, it's now running smoothly. But I'm facing another issue now: why does bindcraft.py utilize all the GPUs when I run it? Is there a way to specify and use only a few GPUs?

**Comment by EHHDD2024** [comment]
> Try updating the bindcraft.py file from the latest repo now.

Thank you so much! After updating bindcraft.py, it's now running smoothly. But I'm facing another issue now: why does bindcraft.py utilize all the GPUs when I run it? Is there a way to specify and use only a few GPUs?

**Comment by martinpacesa** [comment]
It shouldn't. What if you add this line to bindcraft.py:

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
