### ISSUE TITLE
N or C- termini with low scores but the rest are good

### ISSUE THREAD

**Issue by TimCraigCGPS** [martinpacesa/BindCraft#79]
Hi,  I came across what I think may be an interesting example and am looking to get your input on what parameters I might be able to relax.  I have an example trajectory (using default settings) that looks like this:

![image](https://github.com/user-attachments/assets/30e36c70-3c41-4eda-bb7f-60c2f61c00f0)

The N-term 4 residues especially seem quite floppy, but the rest of the binder looks quite nice (the green helix above the binder on the right side is part of the target).  I wonder if there may be a way to identify cases like this and to trim them.

**Comment by martinpacesa** [comment]
Yeah I guess you could trim them by pLDDT value from each end. But generally the floppy parts are not aproblem.
