### ISSUE TITLE
uniqueness of the binder sequences (question).

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#81]
If two different operators use the same parameters to run against the same target PDB file, is that possible for them to get the same hit(s) as an outcome?

Thanks!

**Comment by martinpacesa** [comment]
unlikely, unless you constrain it to very small sizes and specific hotspots. It can always sample 100000 unique trajectories per length and per target. And changing any setting would make it unique again. Protein space is vast.
