### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by agitter** [martinpacesa/BindCraft#82]
I tried running with multiple GPUs (specifically two NVIDIA L40 GPUs) to see if BindCraft could make use of memory across both after I hit
```
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 57664967912 bytes.
```
running on a single GPU.

The code recognized both GPUs, but I encountered the same error. I wanted to confirm this isn't currently supported.

**Comment by martinpacesa** [comment]
No, the BindCraft architecture cannot support multiple GPUs. You can let it overflow into RAM memory if you have DDR5 which is still decently fast.

**Comment by maxall41** [comment]
@martinpacesa How can that be configured?

**Comment by martinpacesa** [comment]
`os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = "2.0"`

Add this to bindcraft.py. The number can be changed to a muliple of your GPU memory. For example if you have 32 Gb GPU RAM and set this number to 2.0, then the RAM it will allocate is 64 Gb + 32 Gb of GPU memory = effectively 96 Gb of memory.

**Comment by yunong782** [comment]
"jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:"


I also had the same issue as agitter, and another prompt mentioned to set "JAX_TRACEBACK_FILTERING=off". I added this script to bindcraft.py script, but it seemed not working. Then I reduced the number of final binder design in target input .json script, it seems running without warning to run out the memory now. But as suggested, the final binder design should be not less than 100, is it? It' running with a number of 80.

**Comment by martinpacesa** [comment]
Hm that should not influence it, as we are not loading the binders into memory. What is your:

1. GPU memory size
2. Target .pdb size in number of amino acids
3. Your binder size range selected

**Comment by yunong782** [comment]
> Hm that should not influence it, as we are not loading the binders into memory. What is your:
> 
> 1. GPU memory size
> 2. Target .pdb size in number of amino acids
> 3. Your binder size range selected

1. GPU size: 	20GB per GPU, we have 4 GPU in service
2. target size: 148 residues
3. binder size range: [55,150]

**Comment by martinpacesa** [comment]
It can only use one GPU per instance, doesn't matter how many you have attached. It could be that the 300 amino acids of target+binder are too large for 20Gb GPU, did not test that size. 500 amino acids are maximum you can fit into 32 Gb memory.

**Comment by martinpacesa** [comment]
What about RAM?

**Comment by YangPH0624** [comment]
> No, the BindCraft architecture cannot support multiple GPUs. You can let it overflow into RAM memory if you have DDR5 which is still decently fast.

My machine has two 4090-24GB GPUs and 128GB of RAM. According to your method, would it be possible to design a 500 amino acid binder-target complex?

**Comment by martinpacesa** [comment]
For 500 you need about 30 Gb I would say

**Comment by cytokineking** [comment]
No that will not work. The Alphafold parameters can only run one one GPU at a time. You can run 2 bindcraft processes, 1 on each GPU, pouring into the same output folder though.
