### ISSUE TITLE
how to find the path to "package manager installation"

### ISSUE THREAD

**Issue by finexzhi** [martinpacesa/BindCraft#9]
Then navigate into your install folder using cd and run the installation code. In pkg_manager specify whether you are using 'mamba' or 'conda' and **in the conda_env specify the path to your package manger installation. For example: /path/to/mambaforge/**

bash install_bindcraft.sh --pkg_manager 'mamba' --conda_env '/path/to/mambaforge/'

I am confused about ' /path/to/mambaforge/'. Do I need to find the location of my package manager installation?

Thanks.

**Comment by martinpacesa** [comment]
Hi,

yes, that would be the path to your package manager installation. However, this is actually a left over from a previous version and is not needed anymore, I just updated the installation script to remove that.
