### ISSUE TITLE
Best practices for trimming target

### ISSUE THREAD

**Issue by athavalechem** [martinpacesa/BindCraft#90]
Any suggestions on how to best trim a target and how much to trim? 

How to best minimize large scale disruptions to the protein structure (at worst) and/or subtle conformational changes at the binding epitope (at best) because of the trimming? Is the trimmed structure passed through AF3 and compared to the full target to make sure there is minimal RMSD and is this attempted multiple times to identify the best trimming? What other things could be done?

**Comment by martinpacesa** [comment]
I would not pass the trimmed structure, as we use a template to constrain the trimmed input so even physically unrealistic trims can be used. We still recommend to use realistic trims though, such as individual domains, ideally something that does not expose core hydrophobics. sometimes this is impossible but we had success with even unrealistic trims. So I suppose you just need to assess whether the binder could still bind to the designed site in the context of the full protein.

**Comment by athavalechem** [comment]
Thanks! Just to clarify - the trimmed structure being constrained is part of the default settings? 
In the preprint, you have a statement which says: "Unlike other design methods, such as RFdiffusion or RIFdock which keep the target backbone fixed during design, BindCraft co-folds both the target and binder at every iteration." Is this contradicting what you are saying about constraining the target?

**Comment by martinpacesa** [comment]
They are not mutually exclusive, the template constrains the target but it doesn't mean it cannot move
