### ISSUE TITLE
Shortlisting from the top 20 designs

### ISSUE THREAD

**Issue by athavalechem** [martinpacesa/BindCraft#91]
Is there any meaningful filter that can be applied to the top 20 designs to narrow down to the top 10 or 5 candidates? What has been your experience?

1. Perhaps just search for diversity of binder length and binding site?
2. On the AF3 server, passing some of the target-binder sequences gives plDDT, pTm and iPTM values slightly different from the Bindcraft calculations. Do you feel using AF3 as a further filter is worthwhile at all?
3. For some of the top 20 designs I see a note: "Relaxed structure contains clashes." Is this of any consequence and should such designs be discarded?

**Comment by martinpacesa** [comment]
1. Higher i_pTM and lower i_pAE scores are more likely to work but generally we like to just sample for diversity from whatever is in Accepted folder.
2. Definitely! More orthogonal predictors can be very helpful
3. We haven't investigated that fully, my intuition tells me it shouldn't be a problem but we put that disclaimer there just in case

**Comment by ajasja** [comment]
Also giving the binders a quick look by eye can't hurt. Other possible metric we use are ddg, SASA, buried unsat hydrogen bonds. Also charge and/or sap score of the binder is also important.

**Comment by TimCraigCGPS** [comment]
> Also giving the binders a quick look by eye can't hurt. Other possible metric we use are ddg, SASA, buried unsat hydrogen bonds. Also charge and/or sap score of the binder is also important.

What ranges are you looking for on those metrics?

**Comment by ajasja** [comment]
These are a bit dependant on case by case (and size of the interface and the protein etc.)
But in general shape_comp>0.6, unsat<=1, charge<-3, ddg<-50
