### ISSUE TITLE
partial redesign of given scaffold?

### ISSUE THREAD

**Issue by paoslaos** [martinpacesa/BindCraft#94]
Dear authors,

I would like to congratulate you on the fine project! In the past I was using ColabDesign for partial redesign around a scaffold of my binder candidate. See here, https://github.com/sokrypton/ColabDesign/tree/main/af#partial-hallucination.

Is this protocol also available in BindCraft or would it be easy to swap the mk_afdesign_model protocol from hallunication to [partial_hallucination](https://github.com/martinpacesa/BindCraft/blob/1163713342a280e758b8610b5e62bb0f57f28af4/bindcraft.py#L202) without too many down stream changes?

Thanks
Sincerely,
P.

**Comment by martinpacesa** [comment]
Right now it is not implemented, we plan to do it next year but not without extensive testing and wetlab validation.

**Comment by paoslaos** [comment]
Many thanks for the swift reply! If I want to experiment myself with it, do you see many difficulties with making the pipeline work or would it be simply enabling the partial hallucination in the snippet I linked above?

**Comment by martinpacesa** [comment]
Hard to say but should work
