### ISSUE TITLE
Difference between peptide_filters.json and filters_peptides.json

### ISSUE THREAD

**Issue by ahmedselim2017** [martinpacesa/BindCraft#95]
Hi, there are two files with a similar name in the settings_filters directory called `peptide_filters.json` (the last commit was "v1.2.0") and `filters_peptides.json` (the last commit was Add files via upload") where the only difference between them is the `peptide_filters.json` has `null` values for `Average_PackStat`, `1_PackStat`, and `2_PackStat` threshold values and `filters_peptides.json` has `0.35`.

**Comment by martinpacesa** [comment]
Whoops, that's a leftover from previous version, will be removed
