### ISSUE TITLE
trajectory repeats good and bad

### ISSUE THREAD

**Issue by mofatuzi** [martinpacesa/BindCraft#96]
The program ran for 4 days, but not a single design was qualified. After checking the trajectory files, I found that the PAE was good during the folding process, but then it worsened, repeating this pattern. Is this normal?
see attachment
![00_00_01--00_00_21](https://github.com/user-attachments/assets/e7200db8-911d-4a6b-92f5-94f932099d1a)

**Comment by martinpacesa** [comment]
Yeah that happens, because it needs to optimise for things other than the interface as well. Maybe the problem is the large disordered parts in your input file?

**Comment by TimCraigCGPS** [comment]
I wonder if the scoring metrics could instead of considering the whole protein instead look at maybe the scoring metrics for the interface residues +X Angstrom (TBD what X would be of course) on the target?

**Comment by mofatuzi** [comment]
> Yeah that happens, because it needs to optimise for things other than the interface as well. Maybe the problem is the large disordered parts in your input file?是的，这种情况发生了，因为它还需要针对界面以外的其他方面进行优化。也许问题是您的输入文件中存在大量无序部分？

Are the disordered parts mean the flexible parts of the structure? How can I improve it? Thanks!

**Comment by TimCraigCGPS** [comment]
> > Yeah that happens, because it needs to optimise for things other than the interface as well. Maybe the problem is the large disordered parts in your input file?是的，这种情况发生了，因为它还需要针对界面以外的其他方面进行优化。也许问题是您的输入文件中存在大量无序部分？
> 
> Are the disordered parts mean the flexible parts of the structure? How can I improve it? Thanks!

Yes- in many cases these are also low pLDDT sections (or high b-factor if template is an x-ray structure).  Trim everything less than 70 in my opinion

**Comment by mofatuzi** [comment]
> > > Yeah that happens, because it needs to optimise for things other than the interface as well. Maybe the problem is the large disordered parts in your input file?是的，这种情况发生了，因为它还需要针对界面以外的其他方面进行优化。也许问题是您的输入文件中存在大量无序部分？
> > 
> > 
> > Are the disordered parts mean the flexible parts of the structure? How can I improve it? Thanks!
> 
> Yes- in many cases these are also low pLDDT sections (or high b-factor if template is an x-ray structure). Trim everything less than 70 in my opinion是的，在许多情况下，这些也是低 pLDDT 切片（如果模板是 X 射线结构，则为高 b 因子）。我认为将所有小于 70 的内容都修剪掉

Thanks a lot!
