### ISSUE TITLE
Pandas EmptyDataError While Fixing Interface Residues

### ISSUE THREAD

**Issue by ahmedselim2017** [martinpacesa/BindCraft#99]
Hi, I was running multiple runs parallelly on multiple GPUs with the same output folder and one of the runs exited with the error below when fixing interface residues.

The runs continued for more than 3 days without an error, and this error has only occurred once. Given the infrequency of the error, is it possible that it is caused by a race condition where one run tries to read a file while the other one is using it?

```
Traceback (most recent call last):
  File "[BindCraft_path]/bindcraft.py", line 396, in <module>
    failure_df = pd.read_csv(failure_csv)
  File "[miniforge3_path]/envs/BindCraft_old/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "[miniforge3_path]/envs/BindCraft_old/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "[miniforge3_path]/envs/BindCraft_old/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "[miniforge3_path]/envs/BindCraft_old/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "[miniforge3_path]/envs/BindCraft_old/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by martinpacesa** [comment]
Yeah, that's probably it, I have seen it before but it only hapened when I ran like 50 jobs at once :D

**Comment by samuelhaysom** [comment]
This looks the same as the issue I raised here: https://github.com/martinpacesa/BindCraft/issues/208. I found it was a big issue when running in parallel across 4-8 gpu cards and basically meant all but one or two would crash in a couple of hours, really reducing throughput.

A dirty fix that worked for me is in the final comment on that issue, pasted here as well:

> Just for info, I did a quick dirty fix for this by putting a loop in to try and read the failures csv file several times before giving up and this has allowed my jobs to run. Looking at the log I think the problem occurs because the program is running the base AF2 filters on all 20 MPNN designs one after the other and is therefore reading/writing to the failure csv file 20 times in quick succession. When two different instances reach this point simultaneously there is a high chance of them running over each other (I've been running across 8 gpus which I guess really increased the chance of this happening for me). I would guess I'm only seeing failures for reading failure CSV and not the other csv files because the other csv files are being read much less frequently, making multiple instances on different gpus unlikely to run over each other.
> 
> There's probably a more elegant solution but this is my code in case anyone else needs this fix:

functions/generic_utils.py line 98. Replace:

`failure_df = pd.read_csv(failure_csv)`

with

```
import time
for attempt in range(1, 11):
    try:
        failure_df = pd.read_csv(failure_csv)
        print(f"Read failure CSV on attempt {attempt}")
        break
    except pd.errors.EmptyDataError:
        if attempt < 10:
            print(f"Failed to read failure CSV on attempt {attempt}, retrying...")
            time.sleep(60)
        else:
            raise
```
